// Diccionario de mapeo fonético para corregir errores comunes del micrófono (Speech-to-Text).
// Añade aquí cualquier palabra o frase que el micrófono entienda mal frecuentemente.
const PHONETIC_MAP: Record<string, string> = {
  // Frontend
  'reak': 'React', 'reap': 'React', 'ríak': 'React', 'riac': 'React', 'riact': 'React', 'reat': 'React', 'rea': 'React', 'react js': 'React', 'riak': 'React', 'ryact': 'React', 'riyak': 'React', 'ri yakt': 'React', 'ryakt': 'React', 'riyakt': 'React', 'rriac': 'React', 'rreak': 'React', 'reack': 'React', 'reackt': 'React', 'riackt': 'React', 'ree act': 'React',
  'viu': 'Vue', 'bue': 'Vue', 'viou': 'Vue', 'vu': 'Vue', 'v i u': 'Vue', 'viue': 'Vue', 'biu': 'Vue', 'byu': 'Vue', 'vyou': 'Vue', 'view js': 'Vue', 'vi yu': 'Vue', 'bi yu': 'Vue', 'vuy': 'Vue', 'buy': 'Vue', 'vyu': 'Vue', 'v y u': 'Vue', 'bi yi u': 'Vue', 'b i u': 'Vue', 'vue js': 'Vue', 'byoo': 'Vue',
  'angulir': 'Angular', 'anjular': 'Angular', 'anguelar': 'Angular', 'anguilar': 'Angular', 'anyular': 'Angular', 'anyilar': 'Angular', 'an gular': 'Angular', 'angulor': 'Angular', 'angu lar': 'Angular', 'anyulor': 'Angular', 'an jular': 'Angular', 'an yular': 'Angular', 'ang yular': 'Angular', 'ang yulor': 'Angular', 'engular': 'Angular', 'en jular': 'Angular', 'en yular': 'Angular', 'anghiular': 'Angular', 'angiular': 'Angular', 'an ghiu lar': 'Angular',
  'taip scrip': 'TypeScript', 'tay script': 'TypeScript', 'taiscript': 'TypeScript', 'ti ai script': 'TypeScript', 'ty script': 'TypeScript', 'tiez': 'TypeScript', 'taipe script': 'TypeScript', 'tayp script': 'TypeScript', 'tai scrip': 'TypeScript', 'ti es script': 'TypeScript', 'taib scrip': 'TypeScript', 'tayb scrip': 'TypeScript', 'tai escript': 'TypeScript', 'tay escript': 'TypeScript', 'taip escrip': 'TypeScript', 'tayp escrip': 'TypeScript', 'ti es scrip': 'TypeScript', 'ti ai scrip': 'TypeScript', 'tai script': 'TypeScript', 'tayp scrip': 'TypeScript',
  'yava script': 'JavaScript', 'yavascrip': 'JavaScript', 'yi es': 'JavaScript', 'yai es': 'JavaScript', 'yota ese': 'JavaScript', 'java scrip': 'JavaScript', 'chaba scrip': 'JavaScript', 'javascrip': 'JavaScript', 'yava scrip': 'JavaScript', 'shava script': 'JavaScript', 'llaba scrip': 'JavaScript', 'llava scrip': 'JavaScript', 'yava escrip': 'JavaScript', 'java escrip': 'JavaScript', 'chava escrip': 'JavaScript', 'shava escrip': 'JavaScript', 'llaba escrip': 'JavaScript', 'llava escrip': 'JavaScript', 'ya va scrip': 'JavaScript', 'ja va scrip': 'JavaScript',
  'nex yei es': 'Next.js', 'nex js': 'Next.js', 'nek js': 'Next.js', 'neks js': 'Next.js', 'next yi es': 'Next.js', 'nes js': 'Next.js', 'nex jeies': 'Next.js', 'next yeies': 'Next.js', 'nes jeies': 'Next.js', 'neks yei es': 'Next.js', 'next jeies': 'Next.js', 'nek jeies': 'Next.js', 'neks jeies': 'Next.js', 'nex yi es': 'Next.js', 'nes yi es': 'Next.js', 'next yies': 'Next.js', 'nex yies': 'Next.js', 'nek yies': 'Next.js', 'neks yies': 'Next.js', 'nes yies': 'Next.js',
  'teil uind': 'Tailwind', 'teluind': 'Tailwind', 'tail uin': 'Tailwind', 'teilwind': 'Tailwind', 'tail guind': 'Tailwind', 'tayl uin': 'Tailwind', 'tei uin': 'Tailwind', 'teil win': 'Tailwind', 'teyl wind': 'Tailwind', 'tel guin': 'Tailwind', 'tayl guind': 'Tailwind', 'teil guind': 'Tailwind', 'teyl guind': 'Tailwind', 'tail wind': 'Tailwind', 'tayl wind': 'Tailwind', 'tail win': 'Tailwind', 'tayl win': 'Tailwind', 'teyl win': 'Tailwind', 'tel win': 'Tailwind', 'tel wind': 'Tailwind',
  'fron en': 'Frontend', 'front en': 'Frontend', 'frond end': 'Frontend', 'fronend': 'Frontend', 'from end': 'Frontend', 'fron ent': 'Frontend', 'front ent': 'Frontend', 'fronent': 'Frontend', 'from ent': 'Frontend', 'fron dent': 'Frontend', 'front end': 'Frontend', 'frond en': 'Frontend', 'from en': 'Frontend', 'fron dend': 'Frontend', 'from dend': 'Frontend', 'fron tent': 'Frontend', 'from tent': 'Frontend', 'front end ': 'Frontend', 'fron en ': 'Frontend', 'from en ': 'Frontend',
  
  // Backend & Base de Datos
  'back en': 'Backend', 'back end': 'Backend', 'bag end': 'Backend', 'bak en': 'Backend', 'bakend': 'Backend', 'bac end': 'Backend', 'bac en': 'Backend', 'bag en': 'Backend', 'back ent': 'Backend', 'bak ent': 'Backend', 'bac ent': 'Backend', 'bag ent': 'Backend', 'bak end': 'Backend', 'back dend': 'Backend', 'bac dend': 'Backend', 'bak dend': 'Backend', 'bag dend': 'Backend', 'back tent': 'Backend', 'bac tent': 'Backend', 'bak tent': 'Backend',
  'nou yei es': 'Node.js', 'noud js': 'Node.js', 'noud': 'Node', 'no je yei es': 'Node.js', 'noot': 'Node.js', 'nod js': 'Node.js', 'noto yei es': 'Node.js', 'node yei es': 'Node.js', 'not yeies': 'Node.js', 'nou yeies': 'Node.js', 'nod yei es': 'Node.js', 'noud yei es': 'Node.js', 'not jeies': 'Node.js', 'nod jeies': 'Node.js', 'nou jeies': 'Node.js', 'noud jeies': 'Node.js', 'not yies': 'Node.js', 'nod yies': 'Node.js', 'nou yies': 'Node.js', 'noud yies': 'Node.js',
  'paiton': 'Python', 'piton': 'Python', 'paizon': 'Python', 'phyton': 'Python', 'pai ton': 'Python', 'paithon': 'Python', 'paitun': 'Python', 'paitom': 'Python', 'payton': 'Python', 'paython': 'Python', 'pay ton': 'Python', 'pay tun': 'Python', 'pai tun': 'Python', 'pay tom': 'Python', 'pai tom': 'Python', 'pai zon': 'Python', 'pay zon': 'Python', 'pei ton': 'Python', 'pei tun': 'Python', 'pei tom': 'Python',
  'yava': 'Java', 'llaba': 'Java', 'chaba': 'Java', 'yaba': 'Java', 'llava': 'Java', 'shaba': 'Java', 'shava': 'Java', 'java': 'Java', 'yavva': 'Java', 'llavva': 'Java', 'yabba': 'Java', 'llabba': 'Java', 'jaba': 'Java', 'jabva': 'Java', 'yabva': 'Java', 'llabva': 'Java', 'chava': 'Java', 'chavva': 'Java', 'chabba': 'Java', 'shabba': 'Java',
  'si charp': 'C#', 'c charp': 'C#', 'ci charp': 'C#', 'c gato': 'C#', 'c michi': 'C#', 'c sharp': 'C#', 'si sharp': 'C#', 'se sharp': 'C#', 'see sharp': 'C#', 'zi charp': 'C#', 'ce charp': 'C#', 'ce sharp': 'C#', 'zee sharp': 'C#', 'zi sharp': 'C#', 'si charb': 'C#', 'ci charb': 'C#', 'ce charb': 'C#', 'si sharb': 'C#', 'ci sharb': 'C#', 'ce sharb': 'C#',
  'esprin but': 'Spring Boot', 'sprint but': 'Spring Boot', 'esprinbot': 'Spring Boot', 'sprimbut': 'Spring Boot', 'springbot': 'Spring Boot', 'esprin boot': 'Spring Boot', 'esprim boot': 'Spring Boot', 'sprint boot': 'Spring Boot', 'esprin vut': 'Spring Boot', 'sprim vut': 'Spring Boot', 'esprin bot': 'Spring Boot', 'sprim bot': 'Spring Boot', 'sprint bot': 'Spring Boot', 'esprin bud': 'Spring Boot', 'sprim bud': 'Spring Boot', 'sprint bud': 'Spring Boot', 'esprin vud': 'Spring Boot', 'sprim vud': 'Spring Boot', 'sprint vud': 'Spring Boot', 'esprin boot ': 'Spring Boot',
  'posgres': 'PostgreSQL', 'posgre': 'PostgreSQL', 'posgres ci cuel': 'PostgreSQL', 'pod gres': 'PostgreSQL', 'post gres': 'PostgreSQL', 'posgreis': 'PostgreSQL', 'posgres kiuel': 'PostgreSQL', 'pos gres': 'PostgreSQL', 'postgress': 'PostgreSQL', 'postgrese': 'PostgreSQL', 'posgres si cuel': 'PostgreSQL', 'posgre si cuel': 'PostgreSQL', 'post gres si cuel': 'PostgreSQL', 'posgres sql': 'PostgreSQL', 'posgre sql': 'PostgreSQL', 'post gres sql': 'PostgreSQL', 'posgres siquel': 'PostgreSQL', 'posgre siquel': 'PostgreSQL', 'post gres siquel': 'PostgreSQL', 'posgres sikel': 'PostgreSQL',
  'mai sico': 'MySQL', 'mai siquel': 'MySQL', 'may sico': 'MySQL', 'mai secuel': 'MySQL', 'maiesecuele': 'MySQL', 'my sicuel': 'MySQL', 'mai ci cuel': 'MySQL', 'may ci cuel': 'MySQL', 'mai es ciu el': 'MySQL', 'may sikel': 'MySQL', 'mai sikel': 'MySQL', 'may siquel': 'MySQL', 'mai zico': 'MySQL', 'may zico': 'MySQL', 'mai sikuel': 'MySQL', 'may sikuel': 'MySQL', 'mai se cuel': 'MySQL', 'may se cuel': 'MySQL', 'mai cico': 'MySQL', 'may cico': 'MySQL',
  'sico': 'SQL', 'sikel': 'SQL', 'sequel': 'SQL', 'secuel': 'SQL', 'es kiu el': 'SQL', 'ece cu ele': 'SQL', 'ese cu ele': 'SQL', 'es ciu el': 'SQL', 'es ciuel': 'SQL', 'zico': 'SQL', 'siquel': 'SQL', 'sikuel': 'SQL', 'se cuel': 'SQL', 'se kuel': 'SQL', 'ze cuel': 'SQL', 'ze kuel': 'SQL', 'es kiuel': 'SQL', 'es kyu el': 'SQL', 'cico': 'SQL', 'zikel': 'SQL',
  'nou sico': 'NoSQL', 'nou siquel': 'NoSQL', 'no es kiu el': 'NoSQL', 'nou secuel': 'NoSQL', 'nou sikel': 'NoSQL', 'now sico': 'NoSQL', 'nou sequel': 'NoSQL', 'no secuel': 'NoSQL', 'no sico': 'NoSQL', 'no siquel': 'NoSQL', 'no sikel': 'NoSQL', 'no sequel': 'NoSQL', 'nou zico': 'NoSQL', 'no zico': 'NoSQL', 'nou sikuel': 'NoSQL', 'no sikuel': 'NoSQL', 'nou cico': 'NoSQL', 'no cico': 'NoSQL', 'nou se cuel': 'NoSQL', 'no se cuel': 'NoSQL',
  'mongo di bi': 'MongoDB', 'mongodb': 'MongoDB', 'mon go de be': 'MongoDB', 'mongo divi': 'MongoDB', 'mongo de be': 'MongoDB', 'mongo dv': 'MongoDB', 'mongo d b': 'MongoDB', 'mongodivi': 'MongoDB', 'mongo db': 'MongoDB', 'mongodebe': 'MongoDB', 'mongo di vi': 'MongoDB', 'mongodibi': 'MongoDB', 'mongo di b': 'MongoDB', 'mongo d v': 'MongoDB', 'mongo dbi': 'MongoDB', 'mongo dvi': 'MongoDB', 'mongo de bi': 'MongoDB', 'mongo de vi': 'MongoDB', 'mon go di bi': 'MongoDB', 'mon go di vi': 'MongoDB',
  
  // DevOps & Cloud
  'doker': 'Docker', 'doca': 'Docker', 'doquer': 'Docker', 'toker': 'Docker', 'darker': 'Docker', 'docar': 'Docker', 'doqer': 'Docker', 'dokar': 'Docker', 'doquere': 'Docker', 'dokere': 'Docker', 'docker': 'Docker', 'dockar': 'Docker', 'doquar': 'Docker', 'docuer': 'Docker', 'docuar': 'Docker', 'doka': 'Docker', 'doqua': 'Docker', 'docka': 'Docker', 'dokee': 'Docker', 'dokir': 'Docker',
  'cubernets': 'Kubernetes', 'kiubernetes': 'Kubernetes', 'ca ocho ese': 'Kubernetes', 'kates': 'Kubernetes', 'cuvernet': 'Kubernetes', 'cuvernetes': 'Kubernetes', 'k8s': 'Kubernetes', 'kiubarnetis': 'Kubernetes', 'cubarnetis': 'Kubernetes', 'cuvernetis': 'Kubernetes', 'kuvernetes': 'Kubernetes', 'kubernetis': 'Kubernetes', 'kuvernetis': 'Kubernetes', 'cubernetes': 'Kubernetes', 'cubernetis': 'Kubernetes', 'ca eigths': 'Kubernetes', 'k eights': 'Kubernetes', 'ku bernets': 'Kubernetes', 'cu bernets': 'Kubernetes', 'ku ver nets': 'Kubernetes',
  'a doble ve ese': 'AWS', 'ei dabliu es': 'AWS', 'au ve ese': 'AWS', 'abedoble ese': 'AWS', 'aws': 'AWS', 'a ve doble ese': 'AWS', 'e dabliu es': 'AWS', 'ei dobliu es': 'AWS', 'ei davliu es': 'AWS', 'a doble u ese': 'AWS', 'ei dabli es': 'AWS', 'ei dobli es': 'AWS', 'e dobliu es': 'AWS', 'e davliu es': 'AWS', 'a doble b ese': 'AWS', 'a be doble ese': 'AWS', 'a doble ue ese': 'AWS', 'a dabliu es': 'AWS', 'a dobliu es': 'AWS', 'a davliu es': 'AWS',
  'ashur': 'Azure', 'ayur': 'Azure', 'azur': 'Azure', 'asure': 'Azure', 'azure': 'Azure', 'achur': 'Azure', 'asshire': 'Azure', 'ayure': 'Azure', 'ashure': 'Azure', 'asshur': 'Azure', 'azhure': 'Azure', 'azhur': 'Azure', 'ashor': 'Azure', 'ashore': 'Azure', 'ayor': 'Azure', 'ayore': 'Azure', 'azor': 'Azure', 'azore': 'Azure', 'asor': 'Azure', 'asore': 'Azure',
  'gisi pi': 'GCP', 'yi ci pi': 'GCP', 'ye se pe': 'GCP', 'yi si pi': 'GCP', 'ye ce pe': 'GCP', 'hi si pi': 'GCP', 'ghi ci pi': 'GCP', 'ghi si pi': 'GCP', 'ye ci pi': 'GCP', 'ye si pi': 'GCP', 'ji si pi': 'GCP', 'ji ci pi': 'GCP', 'lli si pi': 'GCP', 'lli ci pi': 'GCP', 'shi si pi': 'GCP', 'shi ci pi': 'GCP', 'yi zi pi': 'GCP', 'ye zi pe': 'GCP', 'ji zi pi': 'GCP', 'lli zi pi': 'GCP',
  'si ai si di': 'CI/CD', 'c i c d': 'CI/CD', 'sea isede': 'CI/CD', 'ce i ce de': 'CI/CD', 'ci ay ci di': 'CI/CD', 'ci ai ci di': 'CI/CD', 'si ay si di': 'CI/CD', 'ce i se de': 'CI/CD', 'ce y ce de': 'CI/CD', 'ce i ce di': 'CI/CD', 'ci ai si di': 'CI/CD', 'si ai ci di': 'CI/CD', 'ci ay si di': 'CI/CD', 'si ay ci di ': 'CI/CD', 'ce y se de': 'CI/CD', 'se i ce de': 'CI/CD', 'se y ce de': 'CI/CD', 'se i se de': 'CI/CD', 'se y se de': 'CI/CD', 'ci ai si di ': 'CI/CD',
  'yenkins': 'Jenkins', 'yenguins': 'Jenkins', 'jenkins': 'Jenkins', 'genkins': 'Jenkins', 'henkins': 'Jenkins', 'yenkis': 'Jenkins', 'jenkis': 'Jenkins', 'llenguins': 'Jenkins', 'llenkis': 'Jenkins', 'yenquin': 'Jenkins', 'jenquins': 'Jenkins', 'jenquin': 'Jenkins', 'genquins': 'Jenkins', 'genquin': 'Jenkins', 'henquins': 'Jenkins', 'henquin': 'Jenkins', 'shenkins': 'Jenkins', 'shenkis': 'Jenkins', 'shenquins': 'Jenkins', 'shenquin': 'Jenkins',
  'yit lab': 'GitLab', 'git lab': 'GitLab', 'yitlab': 'GitLab', 'gitlab': 'GitLab', 'yid lab': 'GitLab', 'yit lap': 'GitLab', 'git lap': 'GitLab', 'yitlap': 'GitLab', 'jit lab': 'GitLab', 'llit lab': 'GitLab', 'jitlab': 'GitLab', 'llitlab': 'GitLab', 'guit lab': 'GitLab', 'guitlab': 'GitLab', 'yid lab ': 'GitLab', 'yidlap': 'GitLab', 'jit lap': 'GitLab', 'jitlap': 'GitLab', 'llit lap': 'GitLab', 'llitlap': 'GitLab',
  'yit jhab': 'GitHub', 'git hub': 'GitHub', 'yithub': 'GitHub', 'yit jab': 'GitHub', 'git jhab': 'GitHub', 'git jab': 'GitHub', 'yid hub': 'GitHub', 'jit hub': 'GitHub', 'llit hub': 'GitHub', 'llit jab': 'GitHub', 'github': 'GitHub', 'yitjab': 'GitHub', 'gitjhab': 'GitHub', 'gitjab': 'GitHub', 'yidhub': 'GitHub', 'jithub': 'GitHub', 'llithub': 'GitHub', 'llitjab': 'GitHub', 'guit hub': 'GitHub', 'guithub': 'GitHub',
  'yit': 'Git', 'git': 'Git', 'llit': 'Git', 'yid': 'Git', 'jit': 'Git', 'guit': 'Git', 'yit ': 'Git', 'llid': 'Git', 'yete': 'Git', 'llite': 'Git', 'jid': 'Git', 'llid ': 'Git', 'guid': 'Git', 'yite': 'Git', 'gite': 'Git', 'jite': 'Git', 'guite': 'Git', 'yete ': 'Git', 'llite ': 'Git', 'guit ': 'Git',
  'bit baquet': 'Bitbucket', 'bit bucket': 'Bitbucket', 'vid baquet': 'Bitbucket', 'vit baquet': 'Bitbucket', 'vit bucket': 'Bitbucket', 'bid baket': 'Bitbucket', 'bit baket': 'Bitbucket', 'bit baquet ': 'Bitbucket', 'vit baket': 'Bitbucket', 'bit vaquet': 'Bitbucket', 'bitbucket': 'Bitbucket', 'vid bucket': 'Bitbucket', 'vid baket': 'Bitbucket', 'vid vaquet': 'Bitbucket', 'vit vaquet': 'Bitbucket', 'bit vacket': 'Bitbucket', 'vid vacket': 'Bitbucket', 'vit vacket': 'Bitbucket', 'bit bakquet': 'Bitbucket', 'vid bakquet': 'Bitbucket',
  
  // QA Automation & Herramientas
  'gemeter': 'JMeter', 'yeimeter': 'JMeter', 'jota meter': 'JMeter', 'yei miter': 'JMeter', 'yi miter': 'JMeter', 'yemiter': 'JMeter', 'jei meter': 'JMeter', 'jeimeter': 'JMeter', 'yi meter': 'JMeter', 'yey meter': 'JMeter', 'jmeter': 'JMeter', 'jei miter': 'JMeter', 'jeimiter': 'JMeter', 'jota miter': 'JMeter', 'yei mitor': 'JMeter', 'jei mitor': 'JMeter', 'yi mitor': 'JMeter', 'jota mitor': 'JMeter', 'yey miter': 'JMeter', 'yey mitor': 'JMeter',
  'posman': 'Postman', 'potman': 'Postman', 'poxman': 'Postman', 'post man': 'Postman', 'poman': 'Postman', 'pozman': 'Postman', 'pos man': 'Postman', 'postmen': 'Postman', 'posmen': 'Postman', 'pozhman': 'Postman', 'postman': 'Postman', 'pot man': 'Postman', 'pox man': 'Postman', 'po man': 'Postman', 'poz man': 'Postman', 'post men': 'Postman', 'pos men': 'Postman', 'pot men': 'Postman', 'pox men': 'Postman', 'po men': 'Postman',
  'plai raigt': 'Playwright', 'plei rait': 'Playwright', 'plei raig': 'Playwright', 'plei wrigth': 'Playwright', 'plei writ': 'Playwright', 'pleig wrigth': 'Playwright', 'pleig writ': 'Playwright', 'plai rigth': 'Playwright', 'plei rigth': 'Playwright', 'play rigth': 'Playwright', 'play write': 'Playwright', 'play rigt': 'Playwright', 'play wrigth': 'Playwright', 'plei wrait': 'Playwright', 'plai wrait': 'Playwright', 'pleig wrait': 'Playwright', 'pleig rait': 'Playwright', 'pleig raig': 'Playwright', 'pleig rigth': 'Playwright', 'pleig rigt': 'Playwright',
  'sipres': 'Cypress', 'cipres': 'Cypress', 'saipres': 'Cypress', 'caipres': 'Cypress', 'sai pres': 'Cypress', 'cai pres': 'Cypress', 'saypres': 'Cypress', 'caypres': 'Cypress', 'sai prez': 'Cypress', 'cai prez': 'Cypress', 'saiprez': 'Cypress', 'caiprez': 'Cypress', 'sayprez': 'Cypress', 'cayprez': 'Cypress', 'si pres': 'Cypress', 'ci pres': 'Cypress', 'si prez': 'Cypress', 'ci prez': 'Cypress', 'siprez': 'Cypress', 'ciprez': 'Cypress', 'cypress': 'Cypress', 'saipress': 'Cypress', 'cypres': 'Cypress', 'cipress': 'Cypress', 'zaipres': 'Cypress', 'saipres ': 'Cypress', 'cai press': 'Cypress', 'zai pres': 'Cypress', 'zai press': 'Cypress', 'sai press': 'Cypress', 'ci press': 'Cypress', 'zi pres': 'Cypress', 'zi press': 'Cypress',
  'selenion': 'Selenium', 'seleniun': 'Selenium', 'celenion': 'Selenium', 'celeniun': 'Selenium', 'seleniom': 'Selenium', 'celeniom': 'Selenium', 'se le nion': 'Selenium', 'se le niun': 'Selenium', 'ce le nion': 'Selenium', 'ce le niun': 'Selenium', 'se le niom': 'Selenium', 'ce le niom': 'Selenium', 'sele niun': 'Selenium', 'cele niun': 'Selenium', 'sele nion': 'Selenium', 'cele nion': 'Selenium', 'sele niom': 'Selenium', 'cele niom': 'Selenium', 'se leniun': 'Selenium', 'ce leniun': 'Selenium',
  'apium': 'Appium', 'apion': 'Appium', 'eipium': 'Appium', 'apiun': 'Appium', 'apyon': 'Appium', 'epium': 'Appium', 'epiun': 'Appium', 'apyun': 'Appium', 'a pium': 'Appium', 'a pion': 'Appium', 'appium': 'Appium', 'e pion': 'Appium', 'e pium': 'Appium', 'a piun': 'Appium', 'e piun': 'Appium', 'a pyon': 'Appium', 'e pyon': 'Appium', 'a pyun': 'Appium', 'e pyun': 'Appium', 'ei pion': 'Appium',
  'cucumbe': 'Cucumber', 'cucamber': 'Cucumber', 'ququmber': 'Cucumber', 'cucunber': 'Cucumber', 'kiucamber': 'Cucumber', 'quiucamber': 'Cucumber', 'cocamber': 'Cucumber', 'cucamber ': 'Cucumber', 'cucunbe': 'Cucumber', 'cocombe': 'Cucumber', 'cucumber': 'Cucumber', 'cucamberr': 'Cucumber', 'qucumber': 'Cucumber', 'qucamber': 'Cucumber', 'cuqumber': 'Cucumber', 'cuqamber': 'Cucumber', 'kiucumber': 'Cucumber', 'quiucumber': 'Cucumber', 'cocumber': 'Cucumber', 'cucunberr': 'Cucumber',
  'guerquin': 'Gherkin', 'yerkin': 'Gherkin', 'guerkin': 'Gherkin', 'gerkin': 'Gherkin', 'jerkin': 'Gherkin', 'llerkin': 'Gherkin', 'guerkín': 'Gherkin', 'guerquim': 'Gherkin', 'guerkim': 'Gherkin', 'gerquin': 'Gherkin', 'gherkin': 'Gherkin', 'yerquin': 'Gherkin', 'jerquin': 'Gherkin', 'llerquin': 'Gherkin', 'yerquim': 'Gherkin', 'jerquim': 'Gherkin', 'llerquim': 'Gherkin', 'gerquim': 'Gherkin', 'yerkim': 'Gherkin', 'jerkim': 'Gherkin',
  'bi di di': 'BDD', 'be de de': 'BDD', 'vi di di': 'BDD', 've de de': 'BDD', 'bi di di ': 'BDD', 'be de de ': 'BDD', 'vi de de': 'BDD', 'bi de de': 'BDD', 've di di': 'BDD', 'bi de di': 'BDD', 'bdd': 'BDD', 'b d d': 'BDD', 'vi di di ': 'BDD', 've de de ': 'BDD', 'vi de de ': 'BDD', 'bi de de ': 'BDD', 've di di ': 'BDD', 'bi de di ': 'BDD', 'vi di de': 'BDD', 'bi di de': 'BDD',
  'ti di di': 'TDD', 'te de de': 'TDD', 'ti de de': 'TDD', 'te di di': 'TDD', 'te de di': 'TDD', 'ti de di': 'TDD', 'ti di di ': 'TDD', 'te de de ': 'TDD', 'ti de de ': 'TDD', 'te di di ': 'TDD', 'tdd': 'TDD', 't d d': 'TDD', 'te de di ': 'TDD', 'ti de di ': 'TDD', 'ti di de': 'TDD', 'te di de': 'TDD', 'ti di de ': 'TDD', 'te di de ': 'TDD', 'di di di': 'TDD', 'de de de': 'TDD',
  'sonar cub': 'SonarQube', 'sonar cube': 'SonarQube', 'sonarcub': 'SonarQube', 'sonar kiub': 'SonarQube', 'sonar ciub': 'SonarQube', 'zonar cub': 'SonarQube', 'sonar ciube': 'SonarQube', 'sonar qube': 'SonarQube', 'sonar quebe': 'SonarQube', 'sonar cube ': 'SonarQube', 'sonarqube': 'SonarQube', 'zonar cube': 'SonarQube', 'zonarcub': 'SonarQube', 'zonar kiub': 'SonarQube', 'zonar ciub': 'SonarQube', 'zonar ciube': 'SonarQube', 'zonar qube': 'SonarQube', 'zonar quebe': 'SonarQube', 'sonar kyub': 'SonarQube', 'zonar kyub': 'SonarQube',
  'suaguer': 'Swagger', 'suager': 'Swagger', 'esuaguer': 'Swagger', 'zuager': 'Swagger', 'esuager': 'Swagger', 'swaguer': 'Swagger', 'swager': 'Swagger', 'zuaguer': 'Swagger', 'suaguer ': 'Swagger', 'swaguer ': 'Swagger', 'swagger': 'Swagger', 'zuagger': 'Swagger', 'esuagger': 'Swagger', 'suagger': 'Swagger', 'zuaguer ': 'Swagger', 'esuaguer ': 'Swagger', 'swager ': 'Swagger', 'suager ': 'Swagger', 'zuager ': 'Swagger',
  'pe o eme': 'POM', 'pi o em': 'POM', 'pi ou em': 'POM', 'pe ou eme': 'POM', 'p o m': 'POM', 'p o eme': 'POM', 'p o em': 'POM', 'p ou m': 'POM', 'p ou eme': 'POM', 'p ou em': 'POM', 'pi o m': 'POM', 'pe o m': 'POM', 'pi ou m': 'POM', 'pe ou m': 'POM', 'pi o m ': 'POM', 'pe o m ': 'POM', 'pi ou m ': 'POM', 'pe ou m ': 'POM', 'p h m': 'POM', 'pe hache eme': 'POM',
  'peish ovyect': 'Page Object', 'peich ovyect': 'Page Object', 'peish object': 'Page Object', 'peich object': 'Page Object', 'page ovyect': 'Page Object', 'page object': 'Page Object', 'peish obyect': 'Page Object', 'peich obyect': 'Page Object', 'peish ob yect': 'Page Object', 'peich ob yect': 'Page Object', 'page obyect': 'Page Object', 'peish ob jet': 'Page Object', 'peich ob jet': 'Page Object', 'page ob jet': 'Page Object', 'peish objet': 'Page Object', 'peich objet': 'Page Object', 'page objet': 'Page Object', 'pe ish ov yect': 'Page Object', 'pe ich ov yect': 'Page Object', 'pe ish ob ject': 'Page Object',
  'api res': 'API REST', 'api rest': 'API REST', 'ei pi ai rest': 'API REST', 'a pi res': 'API REST', 'ei pi ai res': 'API REST', 'a pi rest': 'API REST', 'api res ': 'API REST', 'api rest ': 'API REST', 'ei pi ai rest ': 'API REST', 'a pi res ': 'API REST', 'apirest': 'API REST', 'apires': 'API REST', 'ei pi ai rest api': 'API REST', 'a pi rest api': 'API REST', 'ei pi ai res api': 'API REST', 'a pi res api': 'API REST', 'api rest api': 'API REST', 'api res api': 'API REST', 'ei pi ay rest': 'API REST', 'ei pi ay res': 'API REST',
  // Duplicate cypress line removed to resolve type check errors
  
  // Metodologías & Conceptos QA
  'itsqb': 'ISTQB', 'ist qb': 'ISTQB', 'ai es ti kiu bi': 'ISTQB', 'y ese te cu be': 'ISTQB', 'is te cu be': 'ISTQB', 'is tqb': 'ISTQB', 'is te q b': 'ISTQB', 'i s t q b': 'ISTQB', 'i ese te cu be': 'ISTQB', 'is t q b': 'ISTQB', 'istqb': 'ISTQB', 'ai es ti kiu vi': 'ISTQB', 'y ese te cu ve': 'ISTQB', 'is te cu ve': 'ISTQB', 'i ese te cu ve': 'ISTQB', 'ai ez ti kiu bi': 'ISTQB', 'ai ez ti kiu vi': 'ISTQB', 'iz te cu be': 'ISTQB', 'iz te cu ve': 'ISTQB', 'i ez te cu be': 'ISTQB',
  'yira': 'Jira', 'jira': 'Jira', 'shira': 'Jira', 'llira': 'Jira', 'yira ': 'Jira', 'jira ': 'Jira', 'shira ': 'Jira', 'llira ': 'Jira', 'gira': 'Jira', 'gira ': 'Jira', 'yiro': 'Jira', 'jiro': 'Jira', 'shiro': 'Jira', 'lliro': 'Jira', 'giro': 'Jira', 'yi ra': 'Jira', 'ji ra': 'Jira', 'shi ra': 'Jira', 'lli ra': 'Jira', 'gi ra': 'Jira',
  'ayail': 'Agile', 'agil': 'Agile', 'ayal': 'Agile', 'eiyail': 'Agile', 'eyail': 'Agile', 'ayil': 'Agile', 'allail': 'Agile', 'ashail': 'Agile', 'ajil': 'Agile', 'ayail ': 'Agile', 'agile': 'Agile', 'ayayl': 'Agile', 'eiyayl': 'Agile', 'eyayl': 'Agile', 'allayl': 'Agile', 'ashayl': 'Agile', 'allil': 'Agile', 'ashil': 'Agile', 'allal': 'Agile', 'ashal': 'Agile',
  'escrum': 'Scrum', 'excrum': 'Scrum', 'esgrun': 'Scrum', 'es cron': 'Scrum', 'es crum': 'Scrum', 'ex crum': 'Scrum', 'es grun': 'Scrum', 'escrum ': 'Scrum', 'excrum ': 'Scrum', 'es crum ': 'Scrum', 'scrum': 'Scrum', 'scrun': 'Scrum', 'escrun': 'Scrum', 'excrun': 'Scrum', 'es crom': 'Scrum', 'es crom ': 'Scrum', 'ex crom': 'Scrum', 'ex crom ': 'Scrum', 's crom': 'Scrum', 's crum': 'Scrum',
  'camban': 'Kanban', 'canban': 'Kanban', 'kanban': 'Kanban', 'kan ban': 'Kanban', 'cam ban': 'Kanban', 'can ban': 'Kanban', 'camban ': 'Kanban', 'canban ': 'Kanban', 'kanban ': 'Kanban', 'kan ban ': 'Kanban', 'canvam': 'Kanban', 'canbam': 'Kanban', 'can vam': 'Kanban', 'can bam': 'Kanban', 'camvam': 'Kanban', 'cambam': 'Kanban', 'cam vam': 'Kanban', 'cam bam': 'Kanban', 'kanvam': 'Kanban', 'kanbam': 'Kanban',
  'esprint': 'Sprint', 'esprin': 'Sprint', 'sprint': 'Sprint', 'sprin': 'Sprint', 'exprint': 'Sprint', 'exprin': 'Sprint', 'esprint ': 'Sprint', 'esprin ': 'Sprint', 'sprint ': 'Sprint', 'sprin ': 'Sprint', 'ezprint': 'Sprint', 'ezprin': 'Sprint', 'ezprint ': 'Sprint', 'ezprin ': 'Sprint', 's print': 'Sprint', 's prin': 'Sprint', 'es print': 'Sprint', 'es prin': 'Sprint', 'ex print': 'Sprint', 'ex prin': 'Sprint',
  'baclog': 'Backlog', 'bac log': 'Backlog', 'baklog': 'Backlog', 'bak log': 'Backlog', 'baglog': 'Backlog', 'bag log': 'Backlog', 'back log': 'Backlog', 'baclog ': 'Backlog', 'bac log ': 'Backlog', 'baklog ': 'Backlog', 'backlog': 'Backlog', 'bak log ': 'Backlog', 'baglog ': 'Backlog', 'bag log ': 'Backlog', 'back log ': 'Backlog', 'backlok': 'Backlog', 'back lok': 'Backlog', 'baclok': 'Backlog', 'bac lok': 'Backlog', 'baklok': 'Backlog',
  'miste cake': 'mistake', 'mis teik': 'mistake', 'mis tek': 'mistake', 'mis teik ': 'mistake', 'mis tek ': 'mistake', 'mistak': 'mistake', 'misteik': 'mistake', 'mistek': 'mistake', 'misteic': 'mistake', 'misteic ': 'mistake', 'mistake': 'mistake', 'miz teik': 'mistake', 'miz tek': 'mistake', 'miz teik ': 'mistake', 'miz tek ': 'mistake', 'miztak': 'mistake', 'mizteik': 'mistake', 'miztek': 'mistake', 'mizteic': 'mistake', 'mizteic ': 'mistake',
  'defect bug false': 'defect bug failure', 'defec bug failur': 'defect bug failure', 'defec bug feilur': 'defect bug failure', 'defec bug feilure': 'defect bug failure', 'defec bag feilur': 'defect bug failure', 'defec bag failur': 'defect bug failure', 'defec bug fail': 'defect bug failure', 'defec bag fail': 'defect bug failure', 'defect bag failur': 'defect bug failure', 'defect bag failure': 'defect bug failure', 'defec bog feilur': 'defect bug failure', 'defec bog failur': 'defect bug failure', 'defec bog fail': 'defect bug failure', 'defect bog failur': 'defect bug failure', 'defect bog failure': 'defect bug failure', 'defect bug feilur': 'defect bug failure', 'defect bug feilure': 'defect bug failure', 'defect bug fail': 'defect bug failure', 'defec bag feilure': 'defect bug failure', 'defect bag feilure': 'defect bug failure',
  'file url': 'failure', 'feilur': 'failure', 'feilure': 'failure', 'failur': 'failure', 'failiur': 'failure', 'feiliur': 'failure', 'file ur': 'failure', 'feylur': 'failure', 'feyliur': 'failure', 'faylur': 'failure', 'failure': 'failure', 'feilior': 'failure', 'failior': 'failure', 'feylior': 'failure', 'faylior': 'failure', 'fayliur': 'failure', 'fail yor': 'failure', 'feil yor': 'failure', 'feil yur': 'failure', 'fail yur': 'failure',
  'yuser stori': 'User Story', 'iusa stori': 'User Story', 'iusar stori': 'User Story', 'iuser stori': 'User Story', 'yusar stori': 'User Story', 'yusa stori': 'User Story', 'iuser story': 'User Story', 'yuser story': 'User Story', 'iusar story': 'User Story', 'yusar story': 'User Story', 'user story': 'User Story', 'iuser estori': 'User Story', 'yuser estori': 'User Story', 'iusa estori': 'User Story', 'yusa estori': 'User Story', 'iusar estori': 'User Story', 'yusar estori': 'User Story', 'iuser estory': 'User Story', 'yuser estory': 'User Story', 'iusa estory': 'User Story',

  // Conceptos Web y Redes
  'ache te te pe': 'HTTP', 'eish ti ti pi': 'HTTP', 'h t t p': 'HTTP', 'eish te te pe': 'HTTP', 'ache ti ti pi': 'HTTP', 'h ti ti pi': 'HTTP', 'h te te pe': 'HTTP', 'ache te ti pi': 'HTTP', 'ache ti te pe': 'HTTP', 'eish ti te pe': 'HTTP', 'http': 'HTTP', 'eish ti ti pi ': 'HTTP', 'ache te te pe ': 'HTTP', 'h t t p ': 'HTTP', 'eish te te pe ': 'HTTP', 'ache ti ti pi ': 'HTTP', 'h ti ti pi ': 'HTTP', 'h te te pe ': 'HTTP', 'ache te ti pi ': 'HTTP', 'ache ti te pe ': 'HTTP',
  'ache te te pe ese': 'HTTPS', 'eish ti ti pi es': 'HTTPS', 'h t t p s': 'HTTPS', 'ache te te pe es': 'HTTPS', 'eish ti ti pi ese': 'HTTPS', 'ache ti ti pi es': 'HTTPS', 'h ti ti pi es': 'HTTPS', 'h te te pe ese': 'HTTPS', 'ache te ti pi es': 'HTTPS', 'ache ti te pe ese': 'HTTPS', 'https': 'HTTPS', 'eish ti ti pi ez': 'HTTPS', 'h t t p z': 'HTTPS', 'ache te te pe ez': 'HTTPS', 'eish ti ti pi eze': 'HTTPS', 'ache ti ti pi ez': 'HTTPS', 'h ti ti pi ez': 'HTTPS', 'h te te pe eze': 'HTTPS', 'ache te ti pi ez': 'HTTPS', 'ache ti te pe eze': 'HTTPS',
  'ti si pi ai pi': 'TCP/IP', 'te ce pe i pe': 'TCP/IP', 'ti si pi i pi': 'TCP/IP', 'te ce pe ai pi': 'TCP/IP', 't c p i p': 'TCP/IP', 'ti ci pi ai pi': 'TCP/IP', 'te se pe i pe': 'TCP/IP', 'ti se pi ai pi': 'TCP/IP', 'te si pe i pe': 'TCP/IP', 'ti si pe i pe': 'TCP/IP', 'tcp/ip': 'TCP/IP', 'te ce pe y pe': 'TCP/IP', 'ti si pi y pi': 'TCP/IP', 'ti ci pi y pi': 'TCP/IP', 'te se pe y pe': 'TCP/IP', 'ti se pi y pi': 'TCP/IP', 'te si pe y pe': 'TCP/IP', 'ti si pe y pe': 'TCP/IP', 'ti si pi ai pe': 'TCP/IP', 'ti ci pi ai pe': 'TCP/IP',
  'gueb soquets': 'WebSockets', 'wepsokets': 'WebSockets', 'gweb soket': 'WebSockets', 'web soquets': 'WebSockets', 'web sokets': 'WebSockets', 'gueb sokets': 'WebSockets', 'wep soquets': 'WebSockets', 'gweb soquets': 'WebSockets', 'web soket': 'WebSockets', 'gueb soket': 'WebSockets', 'websockets': 'WebSockets', 'gueb zoquets': 'WebSockets', 'wepzokets': 'WebSockets', 'gweb zoket': 'WebSockets', 'web zoquets': 'WebSockets', 'web zokets': 'WebSockets', 'gueb zokets': 'WebSockets', 'wep zoquets': 'WebSockets', 'gweb zoquets': 'WebSockets', 'web zoket': 'WebSockets',
  'graf ciu el': 'GraphQL', 'graf kiuel': 'GraphQL', 'graf cuele': 'GraphQL', 'graf cu el': 'GraphQL', 'graf kyu el': 'GraphQL', 'graf q l': 'GraphQL', 'graf q el': 'GraphQL', 'graf q le': 'GraphQL', 'grap q l': 'GraphQL', 'graf cu ele': 'GraphQL', 'graphql': 'GraphQL', 'grap ciu el': 'GraphQL', 'grap kiuel': 'GraphQL', 'grap cuele': 'GraphQL', 'grap cu el': 'GraphQL', 'grap kyu el': 'GraphQL', 'graf ciuel': 'GraphQL', 'grap ciuel': 'GraphQL', 'graf ki u el': 'GraphQL', 'grap ki u el': 'GraphQL',
  'res ful': 'RESTful', 'red ful': 'RESTful', 'resful': 'RESTful', 'redful': 'RESTful', 'rest ful': 'RESTful', 'restful': 'RESTful', 'res full': 'RESTful', 'red full': 'RESTful', 'resfull': 'RESTful', 'redfull': 'RESTful', 'rez ful': 'RESTful', 'rezful': 'RESTful', 'rezt ful': 'RESTful', 'reztful': 'RESTful', 'rez full': 'RESTful', 'rezfull': 'RESTful', 'restfull': 'RESTful', 'rest full': 'RESTful', 'rezt full': 'RESTful', 'reztfull': 'RESTful',
  'maicro fronends': 'Microfrontends', 'micro fron ends': 'Microfrontends', 'maicro fron ends': 'Microfrontends', 'micro fronends': 'Microfrontends', 'maicro frontends': 'Microfrontends', 'micro frontends': 'Microfrontends', 'maicro front ends': 'Microfrontends', 'micro front ends': 'Microfrontends', 'maicro frondends': 'Microfrontends', 'micro frondends': 'Microfrontends', 'microfrontends': 'Microfrontends', 'maicro fronents': 'Microfrontends', 'micro fron ents': 'Microfrontends', 'maicro fron ents': 'Microfrontends', 'micro fronents ': 'Microfrontends', 'maicro frontents': 'Microfrontends', 'micro frontents': 'Microfrontends', 'maicro front ents': 'Microfrontends', 'micro front ents': 'Microfrontends', 'maicro frondents': 'Microfrontends',
  'cukis': 'cookies', 'cuquis': 'cookies', 'cukies': 'cookies', 'cuquies': 'cookies', 'cucis': 'cookies', 'cukis ': 'cookies', 'cuquis ': 'cookies', 'cukies ': 'cookies', 'cuquies ': 'cookies', 'cucis ': 'cookies', 'cookies': 'cookies', 'cukiz': 'cookies', 'cuquiz': 'cookies', 'cukiez': 'cookies', 'cuquiez': 'cookies', 'cuciz': 'cookies', 'cukiz ': 'cookies', 'cuquiz ': 'cookies', 'cukiez ': 'cookies', 'cuquiez ': 'cookies',
  'local estorage': 'LocalStorage', 'local estoresh': 'LocalStorage', 'local storage': 'LocalStorage', 'local storesh': 'LocalStorage', 'loca estorage': 'LocalStorage', 'loca estoresh': 'LocalStorage', 'local estoraj': 'LocalStorage', 'local storaj': 'LocalStorage', 'local estoreish': 'LocalStorage', 'local storeish': 'LocalStorage', 'localstorage': 'LocalStorage', 'loca storage': 'LocalStorage', 'loca storesh': 'LocalStorage', 'loca estoraj': 'LocalStorage', 'loca storaj': 'LocalStorage', 'loca estoreish': 'LocalStorage', 'loca storeish': 'LocalStorage', 'lokal estorage': 'LocalStorage', 'lokal estoresh': 'LocalStorage', 'lokal storage': 'LocalStorage',
  'seshon estorage': 'SessionStorage', 'sesion estorage': 'SessionStorage', 'seshon storage': 'SessionStorage', 'sesion storage': 'SessionStorage', 'seshon estoresh': 'SessionStorage', 'sesion estoresh': 'SessionStorage', 'seshon storesh': 'SessionStorage', 'sesion storesh': 'SessionStorage', 'seshon estoraj': 'SessionStorage', 'sesion estoraj': 'SessionStorage', 'sessionstorage': 'SessionStorage', 'seshon storaj': 'SessionStorage', 'sesion storaj': 'SessionStorage', 'seshon estoreish': 'SessionStorage', 'sesion estoreish': 'SessionStorage', 'seshon storeish': 'SessionStorage', 'sesion storeish': 'SessionStorage', 'sezion estorage': 'SessionStorage', 'sezion storage': 'SessionStorage', 'sezion estoresh': 'SessionStorage',
  'cors': 'CORS', 'corz': 'CORS', 'kors': 'CORS', 'korz': 'CORS', 'corss': 'CORS', 'c or s': 'CORS', 'c o r s': 'CORS', 'c o r z': 'CORS', 'c or z': 'CORS', 'c o r s ': 'CORS', 'c o r z ': 'CORS', 'k or s': 'CORS', 'k o r s': 'CORS', 'k o r z': 'CORS', 'k or z': 'CORS', 'k o r s ': 'CORS', 'k o r z ': 'CORS', 'korss': 'CORS', 'cors ': 'CORS', 'corz ': 'CORS',

  // Roles Ágiles y Habilidades Blandas (Soft Skills)
  'prodac ouner': 'Product Owner', 'prodoc ouna': 'Product Owner', 'produ ouer': 'Product Owner', 'prodak ouner': 'Product Owner', 'prodak ouna': 'Product Owner', 'produ ouner': 'Product Owner', 'prodak ouer': 'Product Owner', 'produc ouner': 'Product Owner', 'produc ouna': 'Product Owner', 'produ c owner': 'Product Owner', 'product owner': 'Product Owner', 'prodac ouna': 'Product Owner', 'prodoc ouner': 'Product Owner', 'produc ouer': 'Product Owner', 'prodac ouer': 'Product Owner', 'prodoc ouer': 'Product Owner', 'produ ouna': 'Product Owner', 'produ k ouner': 'Product Owner', 'produ k ouna': 'Product Owner', 'produ c ouner': 'Product Owner',
  'escrum master': 'Scrum Master', 'ex crum master': 'Scrum Master', 'es crum master': 'Scrum Master', 'escrun master': 'Scrum Master', 'es crun master': 'Scrum Master', 'ex crun master': 'Scrum Master', 'scrum master': 'Scrum Master', 'scrun master': 'Scrum Master', 'escrum maste': 'Scrum Master', 'es crum maste': 'Scrum Master', 'excrum master': 'Scrum Master', 'ex crum maste': 'Scrum Master', 'escrun maste': 'Scrum Master', 'es crun maste': 'Scrum Master', 'ex crun maste': 'Scrum Master', 'scrum maste': 'Scrum Master', 'scrun maste': 'Scrum Master', 'excrum maste': 'Scrum Master', 'es grun master': 'Scrum Master', 'es grun maste': 'Scrum Master',
  'scran': 'Scrum', 'escran': 'Scrum', 'excran': 'Scrum',
  'esteijolders': 'stakeholders', 'esteic jolders': 'stakeholders', 'estey jolders': 'stakeholders', 'estay jolders': 'stakeholders', 'estai jolders': 'stakeholders', 'estei jolders': 'stakeholders', 'estak jolders': 'stakeholders', 'estake jolders': 'stakeholders', 'estake holders': 'stakeholders', 'esteik holders': 'stakeholders', 'stakeholders': 'stakeholders', 'esteijolder': 'stakeholders', 'esteic jolder': 'stakeholders', 'estey jolder': 'stakeholders', 'estay jolder': 'stakeholders', 'estai jolder': 'stakeholders', 'estei jolder': 'stakeholders', 'estak jolder': 'stakeholders', 'estake jolder': 'stakeholders', 'estake holder': 'stakeholders',
  'deili estandap': 'daily standup', 'deili estand ap': 'daily standup', 'deli estandap': 'daily standup', 'deli estand ap': 'daily standup', 'dayli estandap': 'daily standup', 'dayli estand ap': 'daily standup', 'deili standup': 'daily standup', 'deili stand up': 'daily standup', 'deli standup': 'daily standup', 'deli stand up': 'daily standup', 'daily standup': 'daily standup', 'dayli standup': 'daily standup', 'dayli stand up': 'daily standup', 'deili estand up': 'daily standup', 'deli estand up': 'daily standup', 'dayli estand up': 'daily standup', 'deili stan dap': 'daily standup', 'deli stan dap': 'daily standup', 'dayli stan dap': 'daily standup', 'deili stan up': 'daily standup',
  'rifainment': 'refinement', 'rifainmen': 'refinement', 'rifaynment': 'refinement', 'rifaynmen': 'refinement', 'refinement': 'refinement', 'refinemen': 'refinement', 'rifain ment': 'refinement', 'rifain men': 'refinement', 'rifayn ment': 'refinement', 'rifayn men': 'refinement', 'ri fain ment': 'refinement', 'ri fain men': 'refinement', 'ri fayn ment': 'refinement', 'ri fayn men': 'refinement', 're fine ment': 'refinement', 're fine men': 'refinement', 'ri fine ment': 'refinement', 'ri fine men': 'refinement', 're fain ment': 'refinement', 're fain men': 'refinement',
  'retrospectiv': 'retrospective', 'retro': 'retrospective', 'retrospecti': 'retrospective', 'retrospectiva': 'retrospective', 'retrospectibe': 'retrospective', 'retrospectiv ': 'retrospective', 'retro ': 'retrospective', 'retrospecti ': 'retrospective', 'retrospectiva ': 'retrospective', 'retrospectibe ': 'retrospective', 'retrospective': 'retrospective', 'retrospectivv': 'retrospective', 'retrospectivve': 'retrospective', 'retrospectivva': 'retrospective', 'retrospectivv ': 'retrospective', 'retrospectivve ': 'retrospective', 'retrospectivva ': 'retrospective', 're tro': 'retrospective', 're tro spectiv': 'retrospective', 're tro spective': 'retrospective',
  'onbordin': 'onboarding', 'on bordin': 'onboarding', 'onbording': 'onboarding', 'on bording': 'onboarding', 'onboardin': 'onboarding', 'on boardin': 'onboarding', 'onboarding': 'onboarding', 'on boarding': 'onboarding', 'onvordin': 'onboarding', 'on vordin': 'onboarding', 'on vording': 'onboarding', 'onvording': 'onboarding', 'om bordin': 'onboarding', 'ombordin': 'onboarding', 'om bording': 'onboarding', 'ombording': 'onboarding', 'om vordin': 'onboarding', 'omvordin': 'onboarding', 'om vording': 'onboarding', 'omvording': 'onboarding',

  // DevOps y Herramientas CI/CD Extra
  'tera form': 'Terraform', 'terra form': 'Terraform', 'teraform': 'Terraform', 'terraform': 'Terraform', 'tera forn': 'Terraform', 'terra forn': 'Terraform', 'teraforn': 'Terraform', 'terraforn': 'Terraform', 'terrafom': 'Terraform', 'terafom': 'Terraform', 'te ra form': 'Terraform', 'te rra form': 'Terraform', 'te ra forn': 'Terraform', 'te rra forn': 'Terraform', 'te ra fom': 'Terraform', 'te rra fom': 'Terraform', 'terra fom': 'Terraform', 'tera fom': 'Terraform', 'ter ra form': 'Terraform', 'ter a form': 'Terraform',
  'ansibol': 'Ansible', 'ansibel': 'Ansible', 'ansivol': 'Ansible', 'ansivel': 'Ansible', 'ancibol': 'Ansible', 'ancibel': 'Ansible', 'ancivol': 'Ansible', 'ancivel': 'Ansible', 'an sibol': 'Ansible', 'an sibel': 'Ansible', 'ansible': 'Ansible', 'an sivol': 'Ansible', 'an sivel': 'Ansible', 'an cibol': 'Ansible', 'an cibel': 'Ansible', 'an civol': 'Ansible', 'an civel': 'Ansible', 'an si bol': 'Ansible', 'an si bel': 'Ansible', 'an ci bol': 'Ansible',
  'yit jhab acshons': 'GitHub Actions', 'git hub achions': 'GitHub Actions', 'yit hub acshons': 'GitHub Actions', 'git jhab achions': 'GitHub Actions', 'yit hub achions': 'GitHub Actions', 'git jhab acshons': 'GitHub Actions', 'yit jhab achions': 'GitHub Actions', 'git hub acshons': 'GitHub Actions', 'yithub acshons': 'GitHub Actions', 'github achions': 'GitHub Actions', 'github actions': 'GitHub Actions', 'yithub achions': 'GitHub Actions', 'yit jab acshons': 'GitHub Actions', 'git jab achions': 'GitHub Actions', 'yit jab achions': 'GitHub Actions', 'git jab acshons': 'GitHub Actions', 'yitjab acshons': 'GitHub Actions', 'gitjab achions': 'GitHub Actions', 'yitjab achions': 'GitHub Actions', 'gitjab acshons': 'GitHub Actions',
  'sonar claud': 'SonarCloud', 'sonar cloud': 'SonarCloud', 'zonar claud': 'SonarCloud', 'zonar cloud': 'SonarCloud', 'sonarclaud': 'SonarCloud', 'sonarcloud': 'SonarCloud', 'zonarclaud': 'SonarCloud', 'zonarcloud': 'SonarCloud', 'sonar claut': 'SonarCloud', 'sonar clout': 'SonarCloud', 'zonar claut': 'SonarCloud', 'zonar clout': 'SonarCloud', 'sonarclaut': 'SonarCloud', 'sonarclout': 'SonarCloud', 'zonarclaut': 'SonarCloud', 'zonarclout': 'SonarCloud', 'so nar claud': 'SonarCloud', 'so nar cloud': 'SonarCloud', 'zo nar claud': 'SonarCloud', 'zo nar cloud': 'SonarCloud',
  'linus': 'Linux', 'linu': 'Linux', 'linux': 'Linux', 'lynux': 'Linux', 'lynus': 'Linux', 'lynu': 'Linux', 'linos': 'Linux', 'lino': 'Linux', 'lynos': 'Linux', 'lyno': 'Linux', 'li nux': 'Linux', 'li nus': 'Linux', 'li nu': 'Linux', 'ly nux': 'Linux', 'ly nus': 'Linux', 'ly nu': 'Linux', 'li nos': 'Linux', 'li no': 'Linux', 'ly nos': 'Linux', 'ly no': 'Linux',
  'vash': 'Bash', 'bash script': 'Bash', 'bash': 'Bash', 'vash script': 'Bash', 'bach': 'Bash', 'bach script': 'Bash', 'vach': 'Bash', 'vach script': 'Bash', 'baj': 'Bash', 'baj script': 'Bash', 'vaj': 'Bash', 'vaj script': 'Bash', 'ba sh': 'Bash', 'ba sh script': 'Bash', 'va sh': 'Bash', 'va sh script': 'Bash', 'ba ch': 'Bash', 'ba ch script': 'Bash', 'va ch': 'Bash', 'va ch script': 'Bash',

  // Tipos de Pruebas (Testing Types)
  'iunit testin': 'unit testing', 'yunit testin': 'unit testing', 'iunit test': 'unit testing', 'yunit test': 'unit testing', 'iuni testin': 'unit testing', 'yuni testin': 'unit testing', 'iuni test': 'unit testing', 'yuni test': 'unit testing', 'iunitesting': 'unit testing', 'yunitesting': 'unit testing', 'unit testing': 'unit testing', 'iuni testing': 'unit testing', 'yuni testing': 'unit testing', 'iunit testing': 'unit testing', 'yunit testing': 'unit testing', 'iu nit testin': 'unit testing', 'yu nit testin': 'unit testing', 'iu nit test': 'unit testing', 'yu nit test': 'unit testing', 'iu ni testin': 'unit testing',
  'integrayshon testin': 'integration testing', 'integracion testin': 'integration testing', 'integreishon testin': 'integration testing', 'integracion test': 'integration testing', 'integrayshon test': 'integration testing', 'integreishon test': 'integration testing', 'integration testing': 'integration testing', 'integration test': 'integration testing', 'integracion testing': 'integration testing', 'integrayshon testing': 'integration testing', 'integreishon testing': 'integration testing', 'in te grei shon testin': 'integration testing', 'in te gra cion testin': 'integration testing', 'in te grei shon test': 'integration testing', 'in te gra cion test': 'integration testing', 'in te gray shon testin': 'integration testing', 'in te gray shon test': 'integration testing', 'in te gray shon testing': 'integration testing', 'in te grei shon testing': 'integration testing', 'in te gra cion testing': 'integration testing',
  'en tu en': 'End to End', 'i tu i': 'E2E', 'e dos e': 'E2E', 'end tu end': 'End to End', 'en to en': 'End to End', 'end to end': 'End to End', 'i tu i ': 'E2E', 'e dos e ': 'E2E', 'en tu end': 'End to End', 'end tu en': 'End to End', 'e to e': 'E2E', 'i to i': 'E2E', 'e tu e': 'E2E', 'e to e ': 'E2E', 'i to i ': 'E2E', 'e tu e ': 'E2E', 'ent tu ent': 'End to End', 'ent to ent': 'End to End', 'ent tu en': 'End to End', 'en tu ent': 'End to End',
  'esmouk testin': 'smoke testing', 'esmock testin': 'smoke testing', 'esmok testin': 'smoke testing', 'esmoq testin': 'smoke testing', 'esmouk test': 'smoke testing', 'esmock test': 'smoke testing', 'esmok test': 'smoke testing', 'esmoq test': 'smoke testing', 'smoke testing': 'smoke testing', 'smoke test': 'smoke testing', 'esmouk testing': 'smoke testing', 'esmock testing': 'smoke testing', 'esmok testing': 'smoke testing', 'esmoq testing': 'smoke testing', 'es mouk testin': 'smoke testing', 'es mock testin': 'smoke testing', 'es mok testin': 'smoke testing', 'es moq testin': 'smoke testing', 'es mouk test': 'smoke testing', 'es mock test': 'smoke testing', 'smog testing': 'smoke testing', 'smog test': 'smoke testing', 'right testing it': 'sanity testing', 'smokee': 'smoke',
  'regreshon testin': 'regression testing', 'regresion testin': 'regression testing', 'regreshion testin': 'regression testing', 'regresion test': 'regression testing', 'regreshon test': 'regression testing', 'regreshion test': 'regression testing', 'regression testing': 'regression testing', 'regression test': 'regression testing', 'regresion testing': 'regression testing', 'regreshon testing': 'regression testing', 'regreshion testing': 'regression testing', 're gre shon testin': 'regression testing', 're gre sion testin': 'regression testing', 're gre shion testin': 'regression testing', 're gre shon test': 'regression testing', 're gre sion test': 'regression testing', 're gre shion test': 'regression testing', 're gre shon testing': 'regression testing', 're gre sion testing': 'regression testing', 're gre shion testing': 'regression testing', 'regresión testing': 'regression testing', 'regresion': 'regression testing', 'regration': 'regression testing',
  'performans testin': 'performance testing', 'performan testin': 'performance testing', 'performans test': 'performance testing', 'performan test': 'performance testing', 'performance testing': 'performance testing', 'performance test': 'performance testing', 'performanz testin': 'performance testing', 'performanz test': 'performance testing', 'per formans testin': 'performance testing', 'per forman testin': 'performance testing', 'performans testing': 'performance testing', 'performan testing': 'performance testing', 'performanz testing': 'performance testing', 'per formans test': 'performance testing', 'per forman test': 'performance testing', 'per formans testing': 'performance testing', 'per forman testing': 'performance testing', 'per for mans testin': 'performance testing', 'per for man testin': 'performance testing', 'per for mans test': 'performance testing',
  'loud testin': 'load testing', 'load testin': 'load testing', 'lod testin': 'load testing', 'loud test': 'load testing', 'load test': 'load testing', 'lod test': 'load testing', 'load testing': 'load testing', 'lo ad testin': 'load testing', 'lo ad test': 'load testing', 'lou ad testin': 'load testing', 'loud testing': 'load testing', 'lod testing': 'load testing', 'lou ad test': 'load testing', 'lou ad testing': 'load testing', 'lo ad testing': 'load testing', 'lout testin': 'load testing', 'lot testin': 'load testing', 'lout test': 'load testing', 'lot test': 'load testing', 'lout testing': 'load testing',
  'estres testin': 'stress testing', 'estres testing': 'stress testing', 'estress testin': 'stress testing', 'estress testing': 'stress testing', 'estres test': 'stress testing', 'estress test': 'stress testing', 'stres testin': 'stress testing', 'stres testing': 'stress testing', 'stress testin': 'stress testing', 'stress testing': 'stress testing', 'es tres testin': 'stress testing', 'es tres testing': 'stress testing', 'es tress testin': 'stress testing', 'es tress testing': 'stress testing', 'es tres test': 'stress testing', 'es tress test': 'stress testing', 'ez tres testin': 'stress testing', 'ez tres testing': 'stress testing', 'ez tres test': 'stress testing', 'ez tress test': 'stress testing',
  'mokin': 'mocking', 'mocs': 'mocks', 'moquin': 'mocking', 'mockin': 'mocking', 'moquing': 'mocking', 'mocking': 'mocking', 'mocs ': 'mocks', 'mox': 'mocks', 'moks': 'mocks', 'moqs': 'mocks', 'mo kin': 'mocking', 'mo quin': 'mocking', 'moc in': 'mocking', 'mo king': 'mocking', 'mo quing': 'mocking', 'moc ing': 'mocking', 'mo ks': 'mocks', 'mo qs': 'mocks', 'moc s': 'mocks', 'moc z': 'mocks',
  'estubs': 'stubs', 'stabs': 'stubs', 'estabs': 'stubs', 'stubs': 'stubs', 'estub': 'stubs', 'stab': 'stubs', 'estab': 'stubs', 'stub': 'stubs', 'estups': 'stubs', 'staps': 'stubs', 'es tubs': 'stubs', 'es tabs': 'stubs', 'es tub': 'stubs', 'es tab': 'stubs', 'es tups': 'stubs', 'es taps': 'stubs', 'ez tubs': 'stubs', 'ez tabs': 'stubs', 'ez tub': 'stubs', 'ez tab': 'stubs',

  // Conceptos de Programación & Bases de Datos
  'boid': 'void', 'boyd': 'void', 'void': 'void', 'boid ': 'void', 'boyd ': 'void', 'void ': 'void', 'vo it': 'void', 'bo it': 'void', 'vo id': 'void', 'bo id': 'void', 'boit': 'void', 'boit ': 'void', 'voit': 'void', 'voit ': 'void', 'bui': 'void', 'vui': 'void', 'bu id': 'void', 'vu id': 'void', 'bu it': 'void', 'vu it': 'void',
  'ritorn': 'return', 'riturn': 'return', 'ritar': 'return', 'retorn': 'return', 'return': 'return', 'ritorn ': 'return', 'riturn ': 'return', 'ritar ': 'return', 'retorn ': 'return', 'return ': 'return', 'ri torn': 'return', 'ri turn': 'return', 'ri tar': 'return', 're torn': 'return', 're turn': 'return', 'ri torn ': 'return', 'ri turn ': 'return', 'ri tar ': 'return', 're torn ': 'return', 're turn ': 'return',
  'inser': 'INSERT', 'inzer': 'INSERT', 'insert': 'INSERT', 'inzert': 'INSERT', 'in ser': 'INSERT', 'in zer': 'INSERT', 'in sert': 'INSERT', 'in zert': 'INSERT', 'inser ': 'INSERT', 'inzer ': 'INSERT', 'insert ': 'INSERT', 'inzert ': 'INSERT', 'in ser ': 'INSERT', 'in zer ': 'INSERT', 'in sert ': 'INSERT', 'in zert ': 'INSERT', 'incer': 'INSERT', 'incert': 'INSERT', 'in cer': 'INSERT', 'in cert': 'INSERT',
  'selec': 'SELECT', 'selek': 'SELECT', 'select': 'SELECT', 'seleck': 'SELECT', 'zelec': 'SELECT', 'zelek': 'SELECT', 'zelect': 'SELECT', 'zeleck': 'SELECT', 'selec ': 'SELECT', 'selek ': 'SELECT', 'select ': 'SELECT', 'seleck ': 'SELECT', 'zelec ': 'SELECT', 'zelek ': 'SELECT', 'zelect ': 'SELECT', 'zeleck ': 'SELECT', 'se lec': 'SELECT', 'se lek': 'SELECT', 'se lect': 'SELECT', 'se leck': 'SELECT',
  'apdeit': 'UPDATE', 'opdeit': 'UPDATE', 'update': 'UPDATE', 'abdeit': 'UPDATE', 'obdeit': 'UPDATE', 'ap deit': 'UPDATE', 'op deit': 'UPDATE', 'up deit': 'UPDATE', 'ab deit': 'UPDATE', 'ob deit': 'UPDATE', 'apdeit ': 'UPDATE', 'opdeit ': 'UPDATE', 'update ': 'UPDATE', 'abdeit ': 'UPDATE', 'obdeit ': 'UPDATE', 'ap deyt': 'UPDATE', 'op deyt': 'UPDATE', 'up deyt': 'UPDATE', 'ab deyt': 'UPDATE', 'ob deyt': 'UPDATE',
  'dilit': 'DELETE', 'delite': 'DELETE', 'delete': 'DELETE', 'dilet': 'DELETE', 'di lit': 'DELETE', 'de lite': 'DELETE', 'de lete': 'DELETE', 'di let': 'DELETE', 'dilit ': 'DELETE', 'delite ': 'DELETE', 'delete ': 'DELETE', 'dilet ': 'DELETE', 'di lit ': 'DELETE', 'de lite ': 'DELETE', 'de lete ': 'DELETE', 'di let ': 'DELETE', 'dilitz': 'DELETE', 'delitez': 'DELETE', 'deletez': 'DELETE', 'diletz': 'DELETE',
  'bulian': 'boolean', 'vulian': 'boolean', 'buliano': 'boolean', 'vuliano': 'boolean', 'boolean': 'boolean', 'voolean': 'boolean', 'bulian ': 'boolean', 'vulian ': 'boolean', 'buliano ': 'boolean', 'vuliano ': 'boolean', 'boolean ': 'boolean', 'voolean ': 'boolean', 'bu li an': 'boolean', 'vu li an': 'boolean', 'bu li a no': 'boolean', 'vu li a no': 'boolean', 'boo le an': 'boolean', 'voo le an': 'boolean', 'buliam': 'boolean', 'vuliam': 'boolean',
  'estring': 'string', 'strin': 'string', 'string': 'string', 'estrin': 'string', 'es tring': 'string', 'es trin': 'string', 'estring ': 'string', 'strin ': 'string', 'string ': 'string', 'estrin ': 'string', 'es tring ': 'string', 'es trin ': 'string', 'ez tring': 'string', 'ez trin': 'string', 'eztring': 'string', 'eztrin': 'string', 'ez tring ': 'string', 'ez trin ': 'string', 'eztring ': 'string', 'eztrin ': 'string',
  'inteyer': 'integer', 'intiyer': 'integer', 'integer': 'integer', 'int': 'integer', 'in teyer': 'integer', 'in tiyer': 'integer', 'in teger': 'integer', 'inteyer ': 'integer', 'intiyer ': 'integer', 'integer ': 'integer', 'int ': 'integer', 'in teyer ': 'integer', 'in tiyer ': 'integer', 'in teger ': 'integer', 'inteller': 'integer', 'intiller': 'integer', 'in teller': 'integer', 'in tiller': 'integer', 'intejer': 'integer', 'intijer': 'integer',
  'arrai': 'array', 'arrei': 'array', 'array': 'array', 'arre': 'array', 'a rrai': 'array', 'a rrei': 'array', 'a rray': 'array', 'a rre': 'array', 'arrai ': 'array', 'arrei ': 'array', 'array ': 'array', 'arre ': 'array', 'a rrai ': 'array', 'a rrei ': 'array', 'a rray ': 'array', 'a rre ': 'array', 'arrayy': 'array', 'arreii': 'array', 'a rrayy': 'array', 'a rreii': 'array',
  'obyect': 'object', 'obyet': 'object', 'object': 'object', 'objec': 'object', 'o byect': 'object', 'o byet': 'object', 'o bject': 'object', 'o bjec': 'object', 'obyect ': 'object', 'obyet ': 'object', 'object ': 'object', 'objec ': 'object', 'o byect ': 'object', 'o byet ': 'object', 'o bject ': 'object', 'o bjec ': 'object', 'obyectt': 'object', 'obyett': 'object', 'objectt': 'object', 'objecte': 'object',
  'fanchon': 'function', 'funcion': 'function', 'function': 'function', 'funtion': 'function', 'fan chon': 'function', 'fun cion': 'function', 'func tion': 'function', 'fun tion': 'function', 'fanchon ': 'function', 'funcion ': 'function', 'function ': 'function', 'funtion ': 'function', 'fan chon ': 'function', 'fun cion ': 'function', 'func tion ': 'function', 'fun tion ': 'function', 'fangshon': 'function', 'fang shon': 'function', 'fangshion': 'function', 'fang shion': 'function',
  'metod': 'method', 'metodo': 'method', 'method': 'method', 'me tod': 'method', 'me todo': 'method', 'metod ': 'method', 'metodo ': 'method', 'method ': 'method', 'me tod ': 'method', 'me todo ': 'method', 'methot': 'method', 'methot ': 'method', 'me thod': 'method', 'me thot': 'method', 'me thod ': 'method', 'me thot ': 'method', 'medod': 'method', 'medod ': 'method', 'me dod': 'method', 'me dod ': 'method',
  'clas': 'class', 'clase': 'class', 'class': 'class', 'claz': 'class', 'claze': 'class', 'clas ': 'class', 'clase ': 'class', 'class ': 'class', 'claz ': 'class', 'claze ': 'class', 'klass': 'class', 'klase': 'class', 'klass ': 'class', 'klase ': 'class', 'klaz': 'class', 'klaze': 'class', 'klaz ': 'class', 'klaze ': 'class', 'clacs': 'class', 'clacs ': 'class',
  'interfeis': 'interface', 'interfais': 'interface', 'interface': 'interface', 'interfaz': 'interface', 'in terfeis': 'interface', 'in terfais': 'interface', 'in terface': 'interface', 'in interfaz': 'interface', 'interfeis ': 'interface', 'interfais ': 'interface', 'interface ': 'interface', 'interfaz ': 'interface', 'in terfeis ': 'interface', 'in terfais ': 'interface', 'in terface ': 'interface', 'in interfaz ': 'interface', 'interfeiz': 'interface', 'interfaiz': 'interface', 'in terfeiz': 'interface', 'in terfaiz': 'interface',
  'ei pi ai': 'API', 'api': 'API', 'ei pi ay': 'API', 'a pi i': 'API', 'e pi ai': 'API', 'e pi ay': 'API', 'ei pi ai ': 'API', 'api ': 'API', 'ei pi ay ': 'API', 'a pi i ': 'API', 'e pi ai ': 'API', 'e pi ay ': 'API', 'ai pi i': 'API', 'ai pi i ': 'API', 'ey pi ai': 'API', 'ey pi ay': 'API', 'ey pi ai ': 'API', 'ey pi ay ': 'API', 'ap i': 'API', 'ap i ': 'API',
  'yeison': 'JSON', 'jota son': 'JSON', 'json': 'JSON', 'yei son': 'JSON', 'jei son': 'JSON', 'jay son': 'JSON', 'yeison ': 'JSON', 'jota son ': 'JSON', 'json ': 'JSON', 'yei son ': 'JSON', 'jei son ': 'JSON', 'jay son ': 'JSON', 'jeison': 'JSON', 'jeison ': 'JSON', 'jayson': 'JSON', 'jayson ': 'JSON', 'yeizon': 'JSON', 'yeizon ': 'JSON', 'jeizon': 'JSON', 'jeizon ': 'JSON',
  'equis eme ele': 'XML', 'ex em el': 'XML', 'xml': 'XML', 'equis em el': 'XML', 'ex eme ele': 'XML', 'equis eme ele ': 'XML', 'ex em el ': 'XML', 'xml ': 'XML', 'equis em el ': 'XML', 'ex eme ele ': 'XML', 'ecs em el': 'XML', 'ecs em el ': 'XML', 'ecs eme ele': 'XML', 'ecs eme ele ': 'XML', 'x m l': 'XML', 'x m l ': 'XML', 'ex m l': 'XML', 'ex m l ': 'XML', 'ecs m l': 'XML', 'ecs m l ': 'XML',
  'ce ese ese': 'CSS', 'ci es es': 'CSS', 'css': 'CSS', 'ce es es': 'CSS', 'ci ese ese': 'CSS', 'ce ese ese ': 'CSS', 'ci es es ': 'CSS', 'css ': 'CSS', 'ce es es ': 'CSS', 'ci ese ese ': 'CSS', 'se ese ese': 'CSS', 'si es es': 'CSS', 'se es es': 'CSS', 'si ese ese': 'CSS', 'se ese ese ': 'CSS', 'si es es ': 'CSS', 'se es es ': 'CSS', 'si ese ese ': 'CSS', 'c s s': 'CSS', 'c s s ': 'CSS',
  'trai cach': 'try catch', 'tray cacht': 'try catch', 'try catch': 'try catch', 'trai cacht': 'try catch', 'tray cach': 'try catch', 'trai cat': 'try catch', 'tray cat': 'try catch', 'traicach': 'try catch', 'traycacht': 'try catch', 'trycatch': 'try catch', 'traicacht': 'try catch', 'traycach': 'try catch', 'traicat': 'try catch', 'traycat': 'try catch', 'trai kach': 'try catch', 'tray kacht': 'try catch', 'trai kacht': 'try catch', 'tray kach': 'try catch', 'trai kat': 'try catch', 'tray kat': 'try catch',
  'lup': 'loop', 'loop': 'loop', 'luup': 'loop', 'lub': 'loop', 'lup ': 'loop', 'loop ': 'loop', 'luup ': 'loop', 'lub ': 'loop', 'lo op': 'loop', 'lo op ': 'loop', 'lu p': 'loop', 'lu p ': 'loop', 'luu p': 'loop', 'luu p ': 'loop', 'lu b': 'loop', 'lu b ': 'loop', 'lou p': 'loop', 'lou p ': 'loop', 'loob': 'loop', 'loob ': 'loop',
  'guail': 'while', 'wail': 'while', 'while': 'while', 'guayl': 'while', 'wayl': 'while', 'gual': 'while', 'wal': 'while', 'guail ': 'while', 'wail ': 'while', 'while ': 'while', 'guayl ': 'while', 'wayl ': 'while', 'gual ': 'while', 'wal ': 'while', 'juail': 'while', 'juail ': 'while', 'juayl': 'while', 'juayl ': 'while', 'hwail': 'while', 'hwail ': 'while',
  'if els': 'if else', 'ip els': 'if else', 'if else': 'if else', 'ip else': 'if else', 'if elz': 'if else', 'ip elz': 'if else', 'ifels': 'if else', 'ipels': 'if else', 'ifelse': 'if else', 'ipelse': 'if else', 'ifelz': 'if else', 'ipelz': 'if else', 'if els ': 'if else', 'ip els ': 'if else', 'if else ': 'if else', 'ip else ': 'if else', 'if elz ': 'if else', 'ip elz ': 'if else', 'if elze': 'if else', 'if elze ': 'if else',
  'asinc': 'async', 'asink': 'async', 'async': 'async', 'azin': 'async', 'asyn': 'async', 'asin': 'async', 'asinc ': 'async', 'asink ': 'async', 'async ': 'async', 'azin ': 'async', 'asyn ': 'async', 'asin ': 'async', 'asing': 'async', 'asing ': 'async', 'azing': 'async', 'azing ': 'async', 'azink': 'async', 'azink ': 'async', 'a sinc': 'async', 'a sink': 'async',
  'agueit': 'await', 'aueit': 'await', 'await': 'await', 'aguey': 'await', 'auey': 'await', 'a weyt': 'await', 'a ueit': 'await', 'a gueit': 'await', 'agueit ': 'await', 'aueit ': 'await', 'await ': 'await', 'aguey ': 'await', 'auey ': 'await', 'a weyt ': 'await', 'a ueit ': 'await', 'a gueit ': 'await', 'a wayt': 'await', 'a wayt ': 'await', 'aguait': 'await', 'aguait ': 'await',
  'promis': 'promise', 'promesa': 'promise', 'promise': 'promise', 'promiz': 'promise', 'promizsa': 'promise', 'pro mis': 'promise', 'pro mesa': 'promise', 'pro mise': 'promise', 'promis ': 'promise', 'promesa ': 'promise', 'promise ': 'promise', 'promiz ': 'promise', 'promizsa ': 'promise', 'pro mis ': 'promise', 'pro mesa ': 'promise', 'pro mise ': 'promise', 'pro miz': 'promise', 'pro miz ': 'promise', 'promiss': 'promise', 'promiss ': 'promise',
  'zred': 'thread', 'tred': 'thread', 'hilo': 'thread', 'thread': 'thread', 'thred': 'thread', 'zret': 'thread', 'tret': 'thread', 'zred ': 'thread', 'tred ': 'thread', 'hilo ': 'thread', 'thread ': 'thread', 'thred ': 'thread', 'zret ': 'thread', 'tret ': 'thread', 'z reat': 'thread', 't reat': 'thread', 'z read': 'thread', 't read': 'thread', 'th reat': 'thread', 'th read': 'thread',
  'freimwor': 'framework', 'freinguor': 'framework', 'frameguor': 'framework', 'framework': 'framework', 'freimwork': 'framework', 'freingwork': 'framework', 'framegwork': 'framework', 'freinwor': 'framework', 'freinwork': 'framework', 'freimwor ': 'framework', 'freinguor ': 'framework', 'frameguor ': 'framework', 'framework ': 'framework', 'freimwork ': 'framework', 'freingwork ': 'framework', 'framegwork ': 'framework', 'freinwor ': 'framework', 'freinwork ': 'framework', 'freing guor': 'framework', 'freing guor ': 'framework',
  'laibrari': 'library', 'libreria': 'library', 'library': 'library', 'laibreri': 'library', 'laybrari': 'library', 'laybreri': 'library', 'lai brari': 'library', 'li breria': 'library', 'lai breri': 'library', 'lay brari': 'library', 'laibrari ': 'library', 'libreria ': 'library', 'library ': 'library', 'laibreri ': 'library', 'laybrari ': 'library', 'laybreri ': 'library', 'lai brari ': 'library', 'li breria ': 'library', 'lai breri ': 'library', 'lay brari ': 'library',
  'diploiment': 'deployment', 'diploi': 'deploy', 'deployment': 'deployment', 'deploy': 'deploy', 'deploiment': 'deployment', 'deploi': 'deploy', 'diploment': 'deployment', 'diploimen': 'deployment', 'diploiment ': 'deployment', 'diploi ': 'deploy', 'deployment ': 'deployment', 'deploy ': 'deploy', 'deploiment ': 'deployment', 'deploi ': 'deploy', 'diploment ': 'deployment', 'diploimen ': 'deployment', 'di ploi ment': 'deployment', 'di ploi men': 'deployment', 'de ploi ment': 'deployment', 'de ploi men': 'deployment',
  'baribel': 'variable', 'variable': 'variable', 'variabel': 'variable', 'bariavle': 'variable', 'variavle': 'variable', 'ba ri bel': 'variable', 'va ri a ble': 'variable', 'va ri a bel': 'variable', 'baribel ': 'variable', 'variable ': 'variable', 'variabel ': 'variable', 'bariavle ': 'variable', 'variavle ': 'variable', 'ba ri bel ': 'variable', 'va ri a ble ': 'variable', 'va ri a bel ': 'variable', 'va ria ble': 'variable', 'ba ria ble': 'variable', 'va ria ble ': 'variable', 'ba ria ble ': 'variable',
  'nul': 'null', 'null': 'null', 'nool': 'null', 'noul': 'null', 'nul ': 'null', 'null ': 'null', 'nool ': 'null', 'noul ': 'null', 'nu l': 'null', 'nu ll': 'null', 'nu l ': 'null', 'nu ll ': 'null', 'no l': 'null', 'no ll': 'null', 'no l ': 'null', 'no ll ': 'null', 'nol': 'null', 'noll': 'null', 'nol ': 'null', 'noll ': 'null',
  'andefain': 'undefined', 'ondefain': 'undefined', 'undefined': 'undefined', 'andefin': 'undefined', 'ondefin': 'undefined', 'an defain': 'undefined', 'on defain': 'undefined', 'un defined': 'undefined', 'an defin': 'undefined', 'on defin': 'undefined', 'andefain ': 'undefined', 'ondefain ': 'undefined', 'undefined ': 'undefined', 'andefin ': 'undefined', 'ondefin ': 'undefined', 'an defain ': 'undefined', 'on defain ': 'undefined', 'un defined ': 'undefined', 'an defin ': 'undefined', 'on defin ': 'undefined',
  'colback': 'callback', 'colbak': 'callback', 'callback': 'callback', 'calback': 'callback', 'calbak': 'callback', 'col back': 'callback', 'col bak': 'callback', 'call back': 'callback', 'cal back': 'callback', 'cal bak': 'callback', 'colback ': 'callback', 'colbak ': 'callback', 'callback ': 'callback', 'calback ': 'callback', 'calbak ': 'callback', 'col back ': 'callback', 'col bak ': 'callback', 'call back ': 'callback', 'cal back ': 'callback', 'cal bak ': 'callback',
  'cueri': 'query', 'cueris': 'queries', 'query': 'query', 'queries': 'queries', 'quueri': 'query', 'quueris': 'queries', 'cu eri': 'query', 'cu eris': 'queries', 'qu eri': 'query', 'qu eris': 'queries', 'cueri ': 'query', 'cueris ': 'queries', 'query ': 'query', 'queries ': 'queries', 'quueri ': 'query', 'quueris ': 'queries', 'cu eri ': 'query', 'cu eris ': 'queries', 'qu eri ': 'query', 'qu eris ': 'queries',
  'join': 'JOIN', 'yoin': 'JOIN', 'lloin': 'JOIN', 'shoin': 'JOIN', 'join ': 'JOIN', 'yoin ': 'JOIN', 'lloin ': 'JOIN', 'shoin ': 'JOIN', 'jo in': 'JOIN', 'yo in': 'JOIN', 'llo in': 'JOIN', 'sho in': 'JOIN', 'jo in ': 'JOIN', 'yo in ': 'JOIN', 'llo in ': 'JOIN', 'sho in ': 'JOIN', 'choin': 'JOIN', 'cho in': 'JOIN', 'choin ': 'JOIN', 'cho in ': 'JOIN',
  'le yoin': 'LEFT JOIN', 'left join': 'LEFT JOIN', 'lef yoin': 'LEFT JOIN', 'lef join': 'LEFT JOIN', 'le join': 'LEFT JOIN', 'le lloin': 'LEFT JOIN', 'lef lloin': 'LEFT JOIN', 'left lloin': 'LEFT JOIN', 'le shoin': 'LEFT JOIN', 'lef shoin': 'LEFT JOIN', 'le yoin ': 'LEFT JOIN', 'left join ': 'LEFT JOIN', 'lef yoin ': 'LEFT JOIN', 'lef join ': 'LEFT JOIN', 'le join ': 'LEFT JOIN', 'le lloin ': 'LEFT JOIN', 'lef lloin ': 'LEFT JOIN', 'left lloin ': 'LEFT JOIN', 'le shoin ': 'LEFT JOIN', 'lef shoin ': 'LEFT JOIN',
  'iner yoin': 'INNER JOIN', 'inner join': 'INNER JOIN', 'iner join': 'INNER JOIN', 'inner yoin': 'INNER JOIN', 'iner lloin': 'INNER JOIN', 'inner lloin': 'INNER JOIN', 'iner shoin': 'INNER JOIN', 'inner shoin': 'INNER JOIN', 'i ner yoin': 'INNER JOIN', 'in ner join': 'INNER JOIN', 'iner yoin ': 'INNER JOIN', 'inner join ': 'INNER JOIN', 'iner join ': 'INNER JOIN', 'inner yoin ': 'INNER JOIN', 'iner lloin ': 'INNER JOIN', 'inner lloin ': 'INNER JOIN', 'iner shoin ': 'INNER JOIN', 'inner shoin ': 'INNER JOIN', 'i ner yoin ': 'INNER JOIN', 'in ner join ': 'INNER JOIN',
  'auter yoin': 'OUTER JOIN', 'outer join': 'OUTER JOIN', 'auter join': 'OUTER JOIN', 'outer yoin': 'OUTER JOIN', 'aoter yoin': 'OUTER JOIN', 'aoter join': 'OUTER JOIN', 'auter lloin': 'OUTER JOIN', 'outer lloin': 'OUTER JOIN', 'auter shoin': 'OUTER JOIN', 'outer shoin': 'OUTER JOIN', 'auter yoin ': 'OUTER JOIN', 'outer join ': 'OUTER JOIN', 'auter join ': 'OUTER JOIN', 'outer yoin ': 'OUTER JOIN', 'aoter yoin ': 'OUTER JOIN', 'aoter join ': 'OUTER JOIN', 'auter lloin ': 'OUTER JOIN', 'outer lloin ': 'OUTER JOIN', 'auter shoin ': 'OUTER JOIN', 'outer shoin ': 'OUTER JOIN',
  'stor prosidyur': 'stored procedure', 'estor prosidyur': 'stored procedure', 'stored procedure': 'stored procedure', 'estored procedure': 'stored procedure', 'stor prosedyur': 'stored procedure', 'estor prosedyur': 'stored procedure', 'stored prosidyur': 'stored procedure', 'estored prosidyur': 'stored procedure', 'stor procedure': 'stored procedure', 'estor procedure': 'stored procedure', 'stor prosidyur ': 'stored procedure', 'estor prosidyur ': 'stored procedure', 'stored procedure ': 'stored procedure', 'estored procedure ': 'stored procedure', 'stor prosedyur ': 'stored procedure', 'estor prosedyur ': 'stored procedure', 'stored prosidyur ': 'stored procedure', 'estored prosidyur ': 'stored procedure', 'stor procedure ': 'stored procedure', 'estor procedure ': 'stored procedure',
  'triguer': 'trigger', 'trigger': 'trigger', 'triger': 'trigger', 'triguar': 'trigger', 'tri guer': 'trigger', 'tri gger': 'trigger', 'tri ger': 'trigger', 'triguer ': 'trigger', 'trigger ': 'trigger', 'triger ': 'trigger', 'triguar ': 'trigger', 'tri guer ': 'trigger', 'tri gger ': 'trigger', 'tri ger ': 'trigger', 'trigeer': 'trigger', 'trigeer ': 'trigger', 'tri geer': 'trigger', 'tri geer ': 'trigger', 'triguere': 'trigger', 'triguere ': 'trigger',
  'bielu': 'value', 'value': 'value', 'valiu': 'value', 'baliu': 'value', 'valyu': 'value', 'balyu': 'value', 'va liu': 'value', 'ba liu': 'value', 'va lyu': 'value', 'ba lyu': 'value', 'bielu ': 'value', 'value ': 'value', 'valiu ': 'value', 'baliu ': 'value', 'valyu ': 'value', 'balyu ': 'value', 'va liu ': 'value', 'ba liu ': 'value', 'va lyu ': 'value', 'ba lyu ': 'value',
  'ki': 'key', 'key': 'key', 'qui': 'key', 'ky': 'key', 'ki ': 'key', 'key ': 'key', 'qui ': 'key', 'ky ': 'key', 'kee': 'key', 'kee ': 'key', 'kie': 'key', 'kie ': 'key', 'kii': 'key', 'kii ': 'key', 'quii': 'key', 'quii ': 'key', 'quie': 'key', 'quie ': 'key', 'qe': 'key', 'qe ': 'key',
  'praimari ki': 'primary key', 'primary key': 'primary key', 'praimary ki': 'primary key', 'primari ki': 'primary key', 'praimari key': 'primary key', 'praimary key': 'primary key', 'primari key': 'primary key', 'prai mari ki': 'primary key', 'pri mary key': 'primary key', 'prai mary ki': 'primary key', 'praimari ki ': 'primary key', 'primary key ': 'primary key', 'praimary ki ': 'primary key', 'primari ki ': 'primary key', 'praimari key ': 'primary key', 'praimary key ': 'primary key', 'primari key ': 'primary key', 'prai mari ki ': 'primary key', 'pri mary key ': 'primary key', 'prai mary ki ': 'primary key',
  'forin ki': 'foreign key', 'foreign key': 'foreign key', 'forein ki': 'foreign key', 'forein key': 'foreign key', 'foring ki': 'foreign key', 'foring key': 'foreign key', 'fo rin ki': 'foreign key', 'fo reign key': 'foreign key', 'fo rein ki': 'foreign key', 'fo ring ki': 'foreign key', 'forin ki ': 'foreign key', 'foreign key ': 'foreign key', 'forein ki ': 'foreign key', 'forein key ': 'foreign key', 'foring ki ': 'foreign key', 'foring key ': 'foreign key', 'fo rin ki ': 'foreign key', 'fo reign key ': 'foreign key', 'fo rein ki ': 'foreign key', 'fo ring ki ': 'foreign key',
  'comit': 'commit', 'commit': 'commit', 'comid': 'commit', 'commid': 'commit', 'co mit': 'commit', 'co mmit': 'commit', 'co mid': 'commit', 'co mmid': 'commit', 'comit ': 'commit', 'commit ': 'commit', 'comid ': 'commit', 'commid ': 'commit', 'co mit ': 'commit', 'co mmit ': 'commit', 'co mid ': 'commit', 'co mmid ': 'commit', 'c omit': 'commit', 'c omit ': 'commit', 'c ommit': 'commit', 'c ommit ': 'commit',
  'pushear': 'push', 'push': 'push', 'pushar': 'push', 'pusheo': 'push', 'pu sh': 'push', 'pus hear': 'push', 'pus har': 'push', 'pus heo': 'push', 'pushear ': 'push', 'push ': 'push', 'pushar ': 'push', 'pusheo ': 'push', 'pu sh ': 'push', 'pus hear ': 'push', 'pus har ': 'push', 'pus heo ': 'push', 'pushh': 'push', 'pushh ': 'push', 'puch': 'push', 'puch ': 'push',
  'pulear': 'pull', 'pull': 'pull', 'pular': 'pull', 'puleo': 'pull', 'pul': 'pull', 'pu ll': 'pull', 'pul ear': 'pull', 'pul ar': 'pull', 'pul eo': 'pull', 'pulear ': 'pull', 'pull ': 'pull', 'pular ': 'pull', 'puleo ': 'pull', 'pul ': 'pull', 'pu ll ': 'pull', 'pul ear ': 'pull', 'pul ar ': 'pull', 'pul eo ': 'pull', 'puul': 'pull', 'puul ': 'pull',
  'mersh': 'merge', 'merch': 'merge', 'merge': 'merge', 'mersheo': 'merge', 'mercheo': 'merge', 'mergeo': 'merge', 'mer sh': 'merge', 'mer ch': 'merge', 'mer ge': 'merge', 'mersh ': 'merge', 'merch ': 'merge', 'merge ': 'merge', 'mersheo ': 'merge', 'mercheo ': 'merge', 'mergeo ': 'merge', 'mer sh ': 'merge', 'mer ch ': 'merge', 'mer ge ': 'merge', 'mery': 'merge', 'mery ': 'merge',
  'bransh': 'branch', 'branch': 'branch', 'brach': 'branch', 'brans': 'branch', 'bran sh': 'branch', 'bran ch': 'branch', 'bra ch': 'branch', 'bran s': 'branch', 'bransh ': 'branch', 'branch ': 'branch', 'brach ': 'branch', 'brans ': 'branch', 'bran sh ': 'branch', 'bran ch ': 'branch', 'bra ch ': 'branch', 'bran s ': 'branch', 'branz': 'branch', 'branz ': 'branch', 'bran z': 'branch', 'bran z ': 'branch',
  'repo': 'repository', 'ripo': 'repository', 'repository': 'repository', 'repositori': 'repository', 'repositorio': 'repository', 're po': 'repository', 'ri po': 'repository', 're po si to ri': 'repository', 're po si to rio': 'repository', 'repo ': 'repository', 'ripo ': 'repository', 'repository ': 'repository', 'repositori ': 'repository', 'repositorio ': 'repository', 're po ': 'repository', 'ri po ': 'repository', 're po si to ri ': 'repository', 're po si to rio ': 'repository', 'reppo': 'repository', 'reppo ': 'repository',
  'maicroservis': 'microservicio', 'microservicio': 'microservicio', 'micro servicio': 'microservicio', 'microservice': 'microservicio', 'micro service': 'microservicio', 'maicro servis': 'microservicio', 'mai cro ser vis': 'microservicio', 'mi cro ser vi cio': 'microservicio', 'maicroservice': 'microservicio', 'mai cro ser vice': 'microservicio', 'maicroservis ': 'microservicio', 'microservicio ': 'microservicio', 'micro servicio ': 'microservicio', 'microservice ': 'microservicio', 'micro service ': 'microservicio', 'maicro servis ': 'microservicio', 'mai cro ser vis ': 'microservicio', 'mi cro ser vi cio ': 'microservicio', 'maicroservice ': 'microservicio', 'mai cro ser vice ': 'microservicio',
  'monolito': 'monolith', 'monolith': 'monolith', 'monolit': 'monolith', 'mono lito': 'monolith', 'mono lith': 'monolith', 'mono lit': 'monolith', 'mo no li to': 'monolith', 'mo no lith': 'monolith', 'mo no lit': 'monolith', 'monolito ': 'monolith', 'monolith ': 'monolith', 'monolit ': 'monolith', 'mono lito ': 'monolith', 'mono lith ': 'monolith', 'mono lit ': 'monolith', 'mo no li to ': 'monolith', 'mo no lith ': 'monolith', 'mo no lit ': 'monolith', 'monolitho': 'monolith', 'monolitho ': 'monolith',
  'res a pi': 'REST API', 'rest api': 'REST API', 'rest a pi': 'REST API', 'res api': 'REST API', 'res ei pi ai': 'REST API', 'rest ei pi ai': 'REST API', 'res ei pi ay': 'REST API', 'rest ei pi ay': 'REST API', 'rez a pi': 'REST API', 'rez api': 'REST API', 'res a pi ': 'REST API', 'rest api ': 'REST API', 'rest a pi ': 'REST API', 'res api ': 'REST API', 'res ei pi ai ': 'REST API', 'rest ei pi ai ': 'REST API', 'res ei pi ay ': 'REST API', 'rest ei pi ay ': 'REST API', 'rez a pi ': 'REST API', 'rez api ': 'REST API',
  'end poin': 'endpoint', 'endpoint': 'endpoint', 'end point': 'endpoint', 'en poin': 'endpoint', 'en point': 'endpoint', 'end poin ': 'endpoint', 'end point ': 'endpoint', 'en poin ': 'endpoint', 'en point ': 'endpoint', 'ent poin': 'endpoint', 'endpoint ': 'endpoint', 'ent point': 'endpoint', 'em poin': 'endpoint', 'em point': 'endpoint', 'emp point': 'endpoint', 'emp poin': 'endpoint', 'ent poin ': 'endpoint', 'ent point ': 'endpoint', 'em poin ': 'endpoint', 'em point ': 'endpoint',
  'midelguer': 'middleware', 'middleware': 'middleware', 'midleware': 'middleware', 'midelware': 'middleware', 'midle wear': 'middleware', 'midel wear': 'middleware', 'midle uear': 'middleware', 'midel uear': 'middleware', 'midelguer ': 'middleware', 'middleware ': 'middleware', 'midleware ': 'middleware', 'midelware ': 'middleware', 'midle wear ': 'middleware', 'midel wear ': 'middleware', 'midle uear ': 'middleware', 'midel uear ': 'middleware', 'middle wear': 'middleware', 'middle wear ': 'middleware', 'middle ware': 'middleware', 'middle ware ': 'middleware',
  'outentikeishon': 'authentication', 'authentication': 'authentication', 'autenticacion': 'authentication', 'autentikeishon': 'authentication', 'outenticacion': 'authentication', 'ou ten ti kei shon': 'authentication', 'au ten ti ca cion': 'authentication', 'au ten ti kei shon': 'authentication', 'ou ten ti ca cion': 'authentication', 'outentikeishon ': 'authentication', 'authentication ': 'authentication', 'autenticacion ': 'authentication', 'autentikeishon ': 'authentication', 'outenticacion ': 'authentication', 'ou ten ti kei shon ': 'authentication', 'au ten ti ca cion ': 'authentication', 'au ten ti kei shon ': 'authentication', 'ou ten ti ca cion ': 'authentication', 'au ten ti cation': 'authentication', 'au ten ti cation ': 'authentication',
  'otorizeishon': 'authorization', 'authorization': 'authorization', 'autorizacion': 'authorization', 'autorizeishon': 'authorization', 'outorizacion': 'authorization', 'o to ri zei shon': 'authorization', 'au to ri za cion': 'authorization', 'au to ri zei shon': 'authorization', 'ou to ri za cion': 'authorization', 'otorizeishon ': 'authorization', 'authorization ': 'authorization', 'autorizacion ': 'authorization', 'autorizeishon ': 'authorization', 'outorizacion ': 'authorization', 'o to ri zei shon ': 'authorization', 'au to ri za cion ': 'authorization', 'au to ri zei shon ': 'authorization', 'ou to ri za cion ': 'authorization', 'au to ri zation': 'authorization', 'au to ri zation ': 'authorization',
  'llota doble te': 'JWT', 'yota doble te': 'JWT', 'jei doble iu ti': 'JWT', 'llei doble iu ti': 'JWT', 'yei doble iu ti': 'JWT', 'llota be doble te': 'JWT', 'yota be doble te': 'JWT', 'jei be doble ti': 'JWT', 'llei be doble ti': 'JWT', 'yei be doble ti': 'JWT', 'j w t': 'JWT', 'll w t': 'JWT', 'y w t': 'JWT', 'j w ti': 'JWT', 'll w ti': 'JWT', 'y w ti': 'JWT', 'j w t ': 'JWT', 'll w t ': 'JWT', 'y w t ': 'JWT', 'j w ti ': 'JWT', 'token v': 'Token JWT', 'jwt v': 'Token JWT', 'jwt': 'JWT', 'jei dobliu ti': 'JWT', 'jota ve doble te': 'JWT', 'yei dobliu ti': 'JWT', 'jei dobel iu ti': 'JWT', 'to ken': 'JWT', 'token ': 'JWT', 'jwt ': 'JWT', 'jei dobliu ti ': 'JWT', 'jota ve doble te ': 'JWT', 'yei dobliu ti ': 'JWT', 'yei dobel iu ti ': 'JWT', 'to ken ': 'JWT', 'touken': 'JWT', 'tou ken': 'JWT',

  // API y Métodos de Playwright
  'peich go tu': 'page.goto', 'peich gotu': 'page.goto', 'pey gotu': 'page.goto', 'peich gou tu': 'page.goto', 'peig go tu': 'page.goto', 'page gotu': 'page.goto', 'page goto': 'page.goto', 'peish go tu': 'page.goto', 'peish gotu': 'page.goto', 'peij go tu': 'page.goto', 'peich go tu ': 'page.goto', 'peich gotu ': 'page.goto', 'pey gotu ': 'page.goto', 'peich gou tu ': 'page.goto', 'peig go tu ': 'page.goto', 'page gotu ': 'page.goto', 'page goto ': 'page.goto', 'peish go tu ': 'page.goto', 'peish gotu ': 'page.goto', 'peij go tu ': 'page.goto',
  'guet bai rol': 'getByRole', 'get bay rol': 'getByRole', 'get bi rol': 'getByRole', 'guet bay rol': 'getByRole', 'get by rol': 'getByRole', 'get by role': 'getByRole', 'getbyrole': 'getByRole', 'guet by rol': 'getByRole', 'get bai rol': 'getByRole', 'guet bi rol': 'getByRole', 'guet bai rol ': 'getByRole', 'get bay rol ': 'getByRole', 'get bi rol ': 'getByRole', 'guet bay rol ': 'getByRole', 'get by rol ': 'getByRole', 'get by role ': 'getByRole', 'getbyrole ': 'getByRole', 'guet by rol ': 'getByRole', 'get bai rol ': 'getByRole', 'guet bi rol ': 'getByRole',
  'guet bai tex': 'getByText', 'get bay tes': 'getByText', 'get bay text': 'getByText', 'guet by text': 'getByText', 'get by tex': 'getByText', 'get by text': 'getByText', 'getbytext': 'getByText', 'get bai tex': 'getByText', 'get bai text': 'getByText', 'guet bay tes': 'getByText', 'guet bai tex ': 'getByText', 'get bay tes ': 'getByText', 'get bay text ': 'getByText', 'guet by text ': 'getByText', 'get by tex ': 'getByText', 'get by text ': 'getByText', 'getbytext ': 'getByText', 'get bai tex ': 'getByText', 'get bai text ': 'getByText', 'guet bay tes ': 'getByText',
  'fil': 'fill', 'fiil': 'fill', 'phil': 'fill', 'fill': 'fill', 'fil ': 'fill', 'fiil ': 'fill', 'phil ': 'fill', 'fill ': 'fill', 'fi l': 'fill', 'fi ll': 'fill', 'fee l': 'fill', 'feel': 'fill', 'fi l ': 'fill', 'fi ll ': 'fill', 'fee l ': 'fill', 'feel ': 'fill', 'fhil': 'fill', 'fhiil': 'fill', 'fhil ': 'fill', 'fhiil ': 'fill',
  'clic': 'click', 'clik': 'click', 'cliq': 'click', 'click': 'click', 'clic ': 'click', 'clik ': 'click', 'cliq ': 'click', 'click ': 'click', 'cli c': 'click', 'cli ck': 'click', 'cli k': 'click', 'clec': 'click', 'cleck': 'click', 'cli c ': 'click', 'cli ck ': 'click', 'cli k ': 'click', 'clec ': 'click', 'cleck ': 'click', 'clicc': 'click', 'clicc ': 'click',
  'chec': 'check', 'chek': 'check', 'cheq': 'check', 'check': 'check', 'chec ': 'check', 'chek ': 'check', 'cheq ': 'check', 'check ': 'check', 'che c': 'check', 'che ck': 'check', 'che k': 'check', 'chic': 'check', 'chick': 'check', 'che c ': 'check', 'che ck ': 'check', 'che k ': 'check', 'chic ': 'check', 'chick ': 'check', 'checc': 'check', 'checc ': 'check',
  'anchec': 'uncheck', 'unchek': 'uncheck', 'an chek': 'uncheck', 'on chek': 'uncheck', 'uncheck': 'uncheck', 'an chec': 'uncheck', 'on chec': 'uncheck', 'un chek': 'uncheck', 'un chec': 'uncheck', 'an check': 'uncheck', 'anchec ': 'uncheck', 'unchek ': 'uncheck', 'an chek ': 'uncheck', 'on chek ': 'uncheck', 'uncheck ': 'uncheck', 'an chec ': 'uncheck', 'on chec ': 'uncheck', 'un chek ': 'uncheck', 'un chec ': 'uncheck', 'an check ': 'uncheck',
  'gueit for silector': 'waitForSelector', 'weit for selektor': 'waitForSelector', 'wait for selector': 'waitForSelector', 'way for selector': 'waitForSelector', 'guei for silector': 'waitForSelector', 'wey for selector': 'waitForSelector', 'gway for selector': 'waitForSelector', 'waitforselector': 'waitForSelector', 'gueit for selector': 'waitForSelector', 'weit for selector': 'waitForSelector', 'gueit for silector ': 'waitForSelector', 'weit for selektor ': 'waitForSelector', 'wait for selector ': 'waitForSelector', 'way for selector ': 'waitForSelector', 'guei for silector ': 'waitForSelector', 'wey for selector ': 'waitForSelector', 'gway for selector ': 'waitForSelector', 'waitforselector ': 'waitForSelector', 'gueit for selector ': 'waitForSelector', 'weit for selector ': 'waitForSelector',
  'is visibel': 'isVisible', 'is bisibol': 'isVisible', 'is visibol': 'isVisible', 'is visible': 'isVisible', 'iz visible': 'isVisible', 'isvisible': 'isVisible', 'is bisibel': 'isVisible', 'isbisibol': 'isVisible', 'isvisibol': 'isVisible', 'iz visibel': 'isVisible', 'is visibel ': 'isVisible', 'is bisibol ': 'isVisible', 'is visibol ': 'isVisible', 'is visible ': 'isVisible', 'iz visible ': 'isVisible', 'isvisible ': 'isVisible', 'is bisibel ': 'isVisible', 'isbisibol ': 'isVisible', 'isvisibol ': 'isVisible', 'iz visibel ': 'isVisible',
  'escrin chot': 'screenshot', 'escrin shot': 'screenshot', 'skrin shot': 'screenshot', 'escrinchot': 'screenshot', 'escrimchot': 'screenshot', 'screenshot': 'screenshot', 'escrim shot': 'screenshot', 'skrin chot': 'screenshot', 'skrinchot': 'screenshot', 'skrinshot': 'screenshot', 'escrin chot ': 'screenshot', 'escrin shot ': 'screenshot', 'skrin shot ': 'screenshot', 'escrinchot ': 'screenshot', 'escrimchot ': 'screenshot', 'screenshot ': 'screenshot', 'escrim shot ': 'screenshot', 'skrin chot ': 'screenshot', 'skrinchot ': 'screenshot', 'skrinshot ': 'screenshot',
  'coud yen': 'codegen', 'cod yen': 'codegen', 'code jen': 'codegen', 'code yen': 'codegen', 'cou yen': 'codegen', 'codegen': 'codegen', 'cout yen': 'codegen', 'cot yen': 'codegen', 'cou jen': 'codegen', 'cout jen': 'codegen', 'coud yen ': 'codegen', 'cod yen ': 'codegen', 'code jen ': 'codegen', 'code yen ': 'codegen', 'cou yen ': 'codegen', 'codegen ': 'codegen', 'cout yen ': 'codegen', 'cot yen ': 'codegen', 'cou jen ': 'codegen', 'cout jen ': 'codegen',
  'treisin': 'tracing', 'tray sing': 'tracing', 'trei sing': 'tracing', 'traicing': 'tracing', 'tracing': 'tracing', 'trei sin': 'tracing', 'tray sin': 'tracing', 'treicin': 'tracing', 'traycin': 'tracing', 'treysing': 'tracing', 'treisin ': 'tracing', 'tray sing ': 'tracing', 'trei sing ': 'tracing', 'traicing ': 'tracing', 'tracing ': 'tracing', 'trei sin ': 'tracing', 'tray sin ': 'tracing', 'treicin ': 'tracing', 'traycin ': 'tracing', 'treysing ': 'tracing',
  'brauser context': 'browser context', 'brouser context': 'browser context', 'broser context': 'browser context', 'brauzer context': 'browser context', 'browser context': 'browser context', 'brauser contex': 'browser context', 'brouser contex': 'browser context', 'broser contex': 'browser context', 'brauzer contex': 'browser context', 'browser contex': 'browser context', 'brauser context ': 'browser context', 'brouser context ': 'browser context', 'broser context ': 'browser context', 'brauzer context ': 'browser context', 'browser context ': 'browser context', 'brauser contex ': 'browser context', 'brouser contex ': 'browser context', 'broser contex ': 'browser context', 'brauzer contex ': 'browser context', 'browser contex ': 'browser context'
};

export function normalizeTranscription(text: string): string {
  if (!text) return text;
  
  let normalizedText = text;
  
  // Usamos una expresión regular para buscar palabras completas, sin importar mayúsculas o minúsculas.
  for (const [wrongWord, correctWord] of Object.entries(PHONETIC_MAP)) {
    // \\b asegura que coincida con la palabra/frase exacta y no parte de otra palabra
    const regex = new RegExp(`\\b${wrongWord}\\b`, 'gi');
    normalizedText = normalizedText.replace(regex, correctWord);
  }
  
  return normalizedText;
}
